import assert from 'node:assert/strict';
import { reviewedSourceContext } from './src/reviewed-source-context.js';
import { pioneerTransportTopics, PIONEER_TOPIC_SOURCES, PIONEER_SOURCE_URLS, PIONEER_FOCAL_PHRASES } from './src/pioneer-topic-sources.js';
const root='https://www.churchofjesuschrist.org';
const food='/study/ensign/1972/07/a-melting-pot-of-pioneer-recipes';
assert.match(reviewedSourceContext(root+food+'?lang=eng'), /not a source quotation/);
assert.match(reviewedSourceContext(root+food), /not explicitly identified as wagon provisions/);
assert.match(reviewedSourceContext(root+'/study/manual/church-history-in-the-fulness-of-times/chapter-twenty-eight'), /1855/);
for (const url of ['https://example.com'+food, root+food+'-other', 'http://www.churchofjesuschrist.org'+food, 'https://user@www.churchofjesuschrist.org'+food, root+'/study/ensign/1972/07/other']) assert.equal(reviewedSourceContext(url),'');
for (const q of ['Compare wagon and railroad migration.', 'How did hand-cart travel differ from trains?', 'Wagons, handcarts and railways changed emigration.']) assert(pioneerTransportTopics(q,'pioneers').includes(PIONEER_TOPIC_SOURCES.railroad));
assert.deepEqual(pioneerTransportTopics('Compare handcarts and railroad travel.','pioneers'),[PIONEER_TOPIC_SOURCES.railroad,PIONEER_TOPIC_SOURCES.handcart]);
for(const q of ['What did wagon travelers eat?', 'How were handcarts built?', 'When was the railroad completed?']) assert.deepEqual(pioneerTransportTopics(q,'pioneers'),[]);
assert.deepEqual(pioneerTransportTopics('Wagons and trains','ask'),[]);
assert.deepEqual(pioneerTransportTopics(null,'pioneers'),[]);
assert.match(reviewedSourceContext('https://rsc.byu.edu/journey-west/introduction'), /Preserve the word by/);
assert.equal(reviewedSourceContext('https://www.churchofjesuschrist.org/journey-west/introduction'), '');
assert.equal(reviewedSourceContext('https://rsc.byu.edu'+food), '');
assert(PIONEER_SOURCE_URLS.has(PIONEER_TOPIC_SOURCES['camp-routine'].url));
assert.match(PIONEER_TOPIC_SOURCES['camp-routine'].subject, /Gates company in 1853/);
assert(PIONEER_FOCAL_PHRASES['camp-routine'].includes('night'));
assert.match(reviewedSourceContext(root+'/study/manual/primary-5/lesson-39'), /require separate evidence/);
assert.match(reviewedSourceContext('https://rsc.byu.edu/john-lyon-life-pioneer-poet/our-ain-mountain-hame-1853'), /Gates company in 1853/);
assert.match(reviewedSourceContext('https://rsc.byu.edu/their-footsteps/victorian-england'), /October 1852/);
assert(PIONEER_SOURCE_URLS.has(PIONEER_TOPIC_SOURCES['emigration-origins'].url));
assert(PIONEER_SOURCE_URLS.has(PIONEER_TOPIC_SOURCES['migration-patterns'].url));
assert.match(PIONEER_TOPIC_SOURCES['vanguard-journey'].subject, /1847/);
assert.equal(PIONEER_FOCAL_PHRASES['vanguard-journey'],undefined,'discovery vocabulary must not force global chapter26 journey-section scoping');
assert.match(reviewedSourceContext('https://rsc.byu.edu/fire-ice/immigration-utah-early-settlement-spanish-fork'), /unsubstantiated tradition/);
console.log('Reviewed source context QA PASS: exact source boundaries and general transport source diversity.');
