const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const code=fs.readFileSync(path.join(__dirname,'../ask-experience.js'),'utf8');
const dom=new JSDOM('<header class="nav" data-focuschrist-header="standard" style="position:fixed"></header><aside id="askFollowupDock" class="visible" aria-hidden="false"><input></aside><div id="chatBox"><div class="bot-message">John 3:16</div><div class="bot-message">Genesis 1:1</div></div>',{runScripts:'outside-only'});
const w=dom.window,d=w.document,box=d.getElementById('chatBox'),dock=d.getElementById('askFollowupDock'),answer=box.lastElementChild;
Object.defineProperties(w,{innerHeight:{value:900,configurable:true},innerWidth:{value:1366,configurable:true}});
d.querySelector('header').getBoundingClientRect=()=>({height:52});
let pageY=1100,innerY=200;
Object.defineProperty(w,'scrollY',{get:()=>pageY});
w.scrollTo=({top})=>{pageY=top;};
w.matchMedia=()=>({matches:true});
const dockDocumentTop=1000,boxDocumentTop=1132,answerContentTop=1200;
dock.getBoundingClientRect=()=>({top:dockDocumentTop-pageY,height:132,bottom:dockDocumentTop-pageY+132});
box.getBoundingClientRect=()=>({top:boxDocumentTop-pageY,height:500});
answer.getBoundingClientRect=()=>({top:boxDocumentTop-pageY+answerContentTop-innerY,height:300});
Object.defineProperties(box,{scrollHeight:{value:3000},clientHeight:{value:500},scrollTop:{get:()=>innerY}});
box.scrollTo=({top})=>{innerY=top;};
w.eval(code.slice(code.indexOf('    function preferredScrollBehavior('),code.indexOf('    function ensureAskEntryStyles(')));
w.eval(code.slice(code.indexOf('    function focusLatestAnswer('),code.indexOf('    function submitQuestion(')));
w.focusLatestAnswer();
assert.equal(dock.getBoundingClientRect().top,76,'composer begins below fixed header after a follow-up');
assert.equal(answer.getBoundingClientRect().top,226,'latest answer begins just below visible composer');
assert(answer.getBoundingClientRect().top+120<w.innerHeight,'a useful beginning of the answer remains visible');
assert.equal(innerY,1182,'transcript scroll uses actual content coordinates');
Object.defineProperties(w,{innerWidth:{value:390},innerHeight:{value:844,configurable:true}});
w.focusLatestAnswer();
assert.equal(dock.getBoundingClientRect().top,76,'phone completion must preserve the composer below its fixed header');
assert(answer.getBoundingClientRect().top+120<w.innerHeight,'phone must also show the newest answer beginning');
dock.classList.remove('visible');w.focusLatestAnswer();
assert.equal(box.getBoundingClientRect().top,76,'hidden composer must not occupy scroll target');
dock.classList.add('visible');Object.defineProperty(w,'innerHeight',{value:250});w.focusLatestAnswer();
assert.equal(box.getBoundingClientRect().top,76,'short viewport prioritizes answer when both cannot fit');
dom.window.close();console.log('PASS: desktop follow-up composer and latest answer remain visible with fixed header; hidden and short-viewport fallbacks.');
