"""Generate a dedicated Church-source study and the parent introduction."""
from pathlib import Path
import html,json,re
from bs4 import BeautifulSoup
ROOT=Path(__file__).resolve().parents[1]
PARENT=ROOT/'answers/melchizedek-priesthood-restoration.html'
CHILD=ROOT/'answers/race-priesthood-and-temple-blessings.html'
START='<!-- priesthood-blessings-history:start -->'
END='<!-- priesthood-blessings-history:end -->'
esc=lambda s:html.escape(str(s),quote=True)
def link(label,url,cls=''):
    return f'<a class="{cls}" href="{esc(url)}" target="_blank" rel="noopener noreferrer">{esc(label)}</a>'
def prose(text):
    return esc(text).replace('Official Declaration 2',link('Official Declaration 2','https://www.churchofjesuschrist.org/study/scriptures/dc-testament/od/2?lang=eng','fc-inline-scripture'))
def build():
    d=json.loads((ROOT/'docs/priesthood-history/sections.json').read_text(encoding='utf-8'))
    media=json.loads((ROOT/'docs/priesthood-history/visuals.json').read_text(encoding='utf-8'))
    original=PARENT.read_text(encoding='utf-8'); parent=BeautifulSoup(original,'html.parser')
    intro=[START,'<section class="fc-deep-study" id="priesthood-and-temple-blessings" aria-labelledby="priesthood-blessings-heading"><h2 id="priesthood-blessings-heading">Priesthood and temple blessings for all God’s children</h2>',f'<p>{esc(d["parent_introduction"])}</p><p>{esc(d["parent_continuation"])}</p>',f'<div class="fc-actions"><a class="fc-button" href="{CHILD.name}">Explore race, priesthood, and temple blessings</a></div>','<details><summary>Continue with a person or part of the history</summary><ul>']
    for s in d['sections']:intro.append(f'<li id="{s["id"]}"><a href="{CHILD.name}#{s["id"]}">{esc(s["title"])}</a></li>')
    intro+=['</ul></details></section>',END]
    PARENT.write_text(re.sub(re.escape(START)+r'.*?'+re.escape(END),lambda _:'\n'.join(intro),original,flags=re.S),encoding='utf-8',newline='\n')
    url='https://focuschrist.com/answers/'+CHILD.name
    out=['<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">',f'<title>{esc(d["title"])} | focusChrist</title><meta name="description" content="{esc(d["introduction"])}"><meta name="keywords" content="Black Latter-day Saints, race and the priesthood, 1978 revelation, Elijah Able, Jane Manning James, temple blessings"><link rel="canonical" href="{url}">',f'<meta property="og:type" content="article"><meta property="og:site_name" content="focusChrist"><meta property="og:title" content="{esc(d["title"])}"><meta property="og:description" content="{esc(d["introduction"])}"><meta property="og:url" content="{url}"><meta property="og:image" content="{esc(media["revelation-1978"]["image"])}"><meta name="twitter:card" content="summary">']
    styles=['answer-styles.css?v=20261005-centered-pill-labels-1','site-system.css?v=20261005-mobile-study-rows-1','site-header.css?v=20260926-toolbar-readability-1','connected-study.css?v=20260927-anchor-alignment-1','resource-cards.css?v=20260927-anchor-alignment-1','site-search.css?v=20260929-result-hitbox-1','complete-card-rows.css?v=20260920-1','priesthood-history-study.css?v=20260930-2']
    out += [f'<link rel="stylesheet" href="../{c}">' for c in styles]
    out += ['<script src="../site-common.js?v=20261008-section-top-2" defer></script><script src="../site-search.js?v=20260919-focused-answers-1" defer></script></head><body class="fc-site fc-topic-page fc-source-history">',str(parent.select_one('nav[data-focuschrist-header]')),'<header class="fc-source-opening"><div class="fc-container--standard"><p class="fc-eyebrow">Church history · Faith and understanding</p>',f'<h1>{esc(d["title"])}</h1><p>{esc(d["introduction"])}</p>','<div class="fc-actions"><a class="fc-button" href="#begin-study">Begin the study</a><a href="melchizedek-priesthood-restoration.html#priesthood-and-temple-blessings">Return to the priesthood study</a></div><details class="fc-source-directory"><summary>Explore this study</summary><nav class="fc-study-nav" aria-label="On this study page">']
    for s in d['sections']:out.append(f'<a href="#{s["id"]}">{esc(s["title"])}</a>')
    out+=['<a href="#scripture-study">Read the scriptures</a><a href="#guided-practice">Pause and reflect</a><a href="#study-resources">Official sources</a></nav></details></div></header><main class="fc-source-main" id="main-content"><nav class="fc-study-nav" aria-label="Study path"><a href="#restriction-history">History</a><a href="#elijah-able">Elijah</a><a href="#jane-manning-james">Jane</a><a href="#faith-across-nations">Across nations</a><a href="#revelation-1978">The revelation</a><a href="#belonging-and-responsibility">Belonging</a></nav><section class="fc-deep-study" id="begin-study"><p class="fc-eyebrow">Begin with care</p><h2>Sacred blessings and the lives of God’s children</h2><p>For many readers, this history is personal. Approach it with reverence for sacred covenants and respect for the women, men, and families whose lives it affected. This study follows the Church’s published accounts and links to the sources so you can read them in their own context.</p><p>Begin with the Church’s Gospel Topics essay <a href="https://www.churchofjesuschrist.org/study/manual/gospel-topics-essays/race-and-the-priesthood?lang=eng" target="_blank" rel="noopener noreferrer">Race and the Priesthood</a>. Its historical account accompanies the current topic <a href="https://www.churchofjesuschrist.org/study/manual/gospel-topics/race-and-the-church-of-jesus-christ-of-latter-day-saints?lang=eng" target="_blank" rel="noopener noreferrer">Race and The Church of Jesus Christ of Latter-day Saints</a>. Together they guide the history and teachings presented here.</p></section>']
    for i,s in enumerate(d['sections'],1):
        m=media[s['id']]
        out += [f'<section class="fc-deep-study" id="{s["id"]}" aria-labelledby="{s["id"]}-heading"><p class="fc-eyebrow">{i:02d} · Remember and study</p><h2 id="{s["id"]}-heading">{esc(s["title"])}</h2><p>{prose(s["paragraphs"][0])}</p>',f'<div class="fc-resource-grid"><article class="fc-resource-card" data-resource-key="{m["resource_key"]}"><a class="fc-resource-card__image" href="{esc(m["url"])}" target="_blank" rel="noopener noreferrer" aria-label="{esc(m["action"])}"><img src="{esc(m["image"])}" width="{m["width"]}" height="{m["height"]}" alt="{esc(m["alt"])}" loading="lazy" decoding="async"><span class="fc-resource-card__play" aria-hidden="true">▶</span></a><div class="fc-resource-card__body"><p class="fc-resource-card__kind">{esc(m["kind"])}</p><h3>{link(m["action"],m["url"])}</h3><p>{esc(m["caption"])}</p><p class="fc-resource-card__source">{esc(m["credit"])}</p></div></article></div>']
        out += [f'<p>{prose(p)}</p>' for p in s['paragraphs'][1:]]
        out += ['<p class="fc-source-links">'+' '.join(link(x['label'],x['url']) for x in s['sources'])+'</p></section>']
    out+=['<section class="fc-deep-study" id="scripture-study"><h2>Read the scriptures in context</h2><p>Read the revelation in full. Then turn to the Savior’s invitation and the qualities scripture asks of those who serve in His name.</p>']
    purposes=['Read the First Presidency’s letter and the record of the Church’s sustaining vote.','Consider the invitation to come unto Christ and the declaration that all are alike unto God.','Reflect on persuasion, gentleness, love, and the warning against unrighteous dominion.']
    for s,purpose in zip(d['scriptures'],purposes):out.append(f'<p>{link(s["label"],s["url"],"fc-inline-scripture")} · {purpose}</p>')
    out+=['</section><section class="fc-deep-study" id="guided-practice"><h2>Pause and reflect</h2><p>These optional questions are invitations to personal study. Take the time you need.</p><details><summary>Remember the person</summary><p>What did you learn about Elijah’s or Jane’s service, family, and desire to worship? Which part of the official biography would you like to understand more fully?</p></details><details><summary>Read the revelation carefully</summary><p>What does the June 8 letter say about prayer, faithfulness, priesthood, and temple blessings? Keep its words beside the historical account as you study.</p></details><details><summary>Let learning deepen compassion</summary><p>How could this study help you listen more carefully to someone’s experience? What can you do to welcome others and respond to prejudice with courage and kindness?</p></details></section><section class="fc-deep-study" id="study-resources"><h2>Continue with the official sources</h2><p>All historical and doctrinal sources in this study are published by The Church of Jesus Christ of Latter-day Saints. The biographies and global histories are later accounts; <a class="fc-inline-scripture" href="https://www.churchofjesuschrist.org/study/scriptures/dc-testament/od/2?lang=eng" target="_blank" rel="noopener noreferrer">Official Declaration 2</a> preserves the 1978 letter and conference presentation. The illustrated films are Church storytelling, while the conference recording documents the public proceedings.</p><ul>']
    seen=set()
    for s in d['sections']:
        for x in s['sources']:
            if x['url'] not in seen:out.append('<li>'+link(x['label'],x['url'])+'</li>');seen.add(x['url'])
    out+=['</ul></section><section class="fc-deep-study" id="continue-study"><h2>Continue your study</h2><div class="fc-study-grid"><article><h3><a href="melchizedek-priesthood-restoration.html#priesthood-and-temple-blessings">Return to the priesthood study</a></h3><p>Continue learning about priesthood authority and the call to serve.</p></article><article><h3><a href="why-latter-day-saints-build-temples.html">Why Latter-day Saints build temples</a></h3><p>Study the place of covenants and family sealing in temple worship.</p></article><article style="grid-column:1 / -1"><h3><a href="../church-history.html">Explore Church history</a></h3><p>Meet other Saints through their lives and recorded experiences.</p></article></div><div class="fc-actions"><a class="fc-button" href="../ask.html?question=What%20do%20official%20Church%20sources%20teach%20about%20the%201978%20revelation%3F">Ask about this study</a><a href="../answers.html">Choose another study</a></div></section></main>',str(parent.footer),'<script>function toggleMenu(){var m=document.getElementById("hamburgerMenu");if(m)m.classList.toggle("show");}</script></body></html>']
    result='\n'.join(out)
    CHILD.write_text(result,encoding='utf-8',newline='\n')
    from enrich_priesthood_study import enrich
    enrich()
if __name__=='__main__':build()
