// The Covenant picture must stay unique and retain its study panel when moved.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { JSDOM } = require('jsdom');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const dom = new JSDOM(read('answers/abrahamic-covenant.html'), {url:'https://focuschrist.com/answers/abrahamic-covenant.html',runScripts:'outside-only'});
const {window} = dom, {document} = window;
const query = {matches:true,addEventListener(event, callback){this.change=callback;}};
window.matchMedia = () => query;
window.HTMLElement.prototype.scrollIntoView = function(){};
window.HTMLDialogElement.prototype.showModal = function(){this.setAttribute('open','');};
window.HTMLDialogElement.prototype.close = function(){this.removeAttribute('open');this.dispatchEvent(new window.Event('close'));};
for(const name of ['full-image-viewer.js','topic-artwork-details.js','desktop-hero-repairs.js']) window.eval(read(name));
document.dispatchEvent(new window.Event('DOMContentLoaded'));
const picture = document.getElementById('picture-ac-jacob-ladder');
const trigger = picture.querySelector('a');
assert.equal(picture.parentElement,document.querySelector('[data-covenant-hero-slot]'));
assert(trigger.hasAttribute('data-topic-artwork-detail'),'Existing study adapter must bind before relocation');
trigger.click();
const panel = document.getElementById('topicArtworkDetailDialog');
assert(panel.open,'Desktop hero opens study first');
assert.equal(panel.querySelector('h2').textContent,'The Lord is in this place');
assert(panel.querySelector('[data-topic-art-source]').href.includes('/gen/28?'));
assert(panel.querySelector('[data-full-image-viewer]').href.endsWith('/ac-jacob-ladder-full.webp'));
panel.close();
query.matches=false;
assert.equal(picture.parentElement,document.querySelector('[data-covenant-hero-slot]'),'Phone must retain the visible opening hero');
assert.equal(document.querySelector('[data-covenant-hero-slot]').children.length,1);
assert.equal(document.querySelectorAll('#picture-ac-jacob-ladder').length,1,'No duplicate original artwork');
dom.window.close();
console.log('PASS: one Covenant artwork, desktop/mobile opening visibility, study panel and full-size original.');
