const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const assert=require('node:assert/strict');
const script=fs.readFileSync(path.join(__dirname,'../topic-artwork-details.js'),'utf8');
const source=script.match(/        function officialLinks\(container\) \{[\s\S]*?\n        \}/)[0];
function allows(route,href){
 const context={URL,location:{pathname:route},document:{body:{classList:{contains:()=>false}}}};
 vm.createContext(context);
 vm.runInContext(source+'; this.check=officialLinks;',context);
 const link={href,querySelector:()=>null};
 return context.check({querySelectorAll:()=>[link]}).length===1;
}
const route='/joseph-smith-portrait-research.html';
assert(allows(route,'https://archive.org/details/figurespast00quingoog/page/n393/mode/1up'));
assert(allows(route,'https://contentdm.lib.byu.edu/digital/collection/RelEd/id/4109'));
assert(allows(route,'https://commons.wikimedia.org/wiki/File:Joseph_Smith_Maudsley_Portrait_1842-06-25.jpg'));
assert(!allows('/joseph-smith-likeness.html','https://commons.wikimedia.org/wiki/File:Joseph_Smith_Maudsley_Portrait_1842-06-25.jpg'));
assert(!allows(route,'https://commons.wikimedia.org.evil.example/wiki/File:Joseph.jpg'));
assert(!allows(route,'http://commons.wikimedia.org/wiki/File:Joseph.jpg'));
assert(!allows('/joseph-smith-likeness.html','https://contentdm.lib.byu.edu/digital/collection/RelEd/id/4109'));
const maskCatalogue='https://contentdm.lib.byu.edu/digital/collection/RelEd/id/4109/rec/5';
assert(allows('/joseph-smith-likeness.html',maskCatalogue));
assert(!allows('/index.html',maskCatalogue));
assert(!allows('/joseph-smith-likeness.html',maskCatalogue.replace('https:','http:')));
assert(!allows('/joseph-smith-likeness.html',maskCatalogue.replace('.edu/','.edu.evil.example/')));
assert(!allows('/joseph-smith-likeness.html',maskCatalogue.replace('4109','4110')));
assert(!allows(route,'https://contentdm.lib.byu.edu.evil.example/digital/collection/RelEd/id/4109'));
assert(!allows(route,'http://contentdm.lib.byu.edu/digital/collection/RelEd/id/4109'));
assert(!allows('/joseph-smith-likeness.html','https://archive.org/details/example'));
assert(!allows(route,'https://archive.org.example.com/details/example'));
assert(!allows(route,'https://archive.org@evil.example/details/example'));
assert(!allows(route,'http://archive.org/details/example'));
assert(!allows(route,'javascript:alert(1)'));
assert(allows('/joseph-smith-likeness.html','https://www.josephsmithpapers.org/person/joseph-smith-jr'));
assert(allows(route,'https://www.churchofjesuschrist.org/study/scriptures/nt/john/5'));
console.log('PASS: exact research-route Archive.org/BYU/Commons sources; host spoof, other-route, insecure protocol negatives; existing official hosts preserved.');

const quincy='/article/josiah-quincys-1844-visit-with-joseph-smith';
const ledger='/article/david-hales-store-ledger-new-details-about-joseph-and-emma-smith-the-hale-family-and-the-book-of-mormon';
assert(allows(route,'https://byustudies.byu.edu'+quincy));
assert(allows('/joseph-smith-likeness.html','https://byustudies.byu.edu'+ledger));
for (const url of ['https://byustudies.byu.edu/unrelated','https://byustudies.byu.edu.evil.example'+quincy,'http://byustudies.byu.edu'+quincy,'https://byustudies.byu.edu@evil.example'+quincy]) assert(!allows(route,url));
assert(!allows('/index.html','https://byustudies.byu.edu'+quincy));
assert(!allows('/joseph-smith-likeness.html','https://byustudies.byu.edu'+quincy));
assert(!allows(route,'https://byustudies.byu.edu'+ledger));
console.log('PASS exact Joseph route/article BYU Studies destinations, unrelated paths/routes and spoof/insecure negatives.');

const minutes='https://www.churchhistorianspress.org/the-first-fifty-years-of-relief-society/part-1/1-2/1-2-1';
assert(allows('/joseph-smith-likeness.html',minutes));
assert(!allows('/index.html',minutes));
assert(!allows('/joseph-smith-likeness.html',minutes.replace('https:','http:')));
assert(!allows('/joseph-smith-likeness.html',minutes.replace('.org/','.org.evil.example/')));
assert(!allows('/joseph-smith-likeness.html','https://www.churchhistorianspress.org/unrelated'));
