/* Actual Leaflet camera frames; tile pixels simulated, not provider or physical-phone proof. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
function assertCentered(error){assert(error<=1,'Final center within one rendered pixel');}
assertCentered(Math.hypot(.5,.5));assert.throws(()=>assertCentered(1.01));
module.exports=async function(page,origin,out){
 const records=[],dist=path.dirname(require.resolve('leaflet'));
 const intercept=async r=>{const u=r.request().url();if(u.includes('/leaflet@')&&u.endsWith('.js'))return r.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(dist,'leaflet.js'),'utf8')+'\n;window.__cameraMaps=[];const cameraMap=L.map;L.map=function(){const m=cameraMap.apply(this,arguments);window.__cameraMaps.push(m);return m;};'});if(u.includes('leaflet')&&u.endsWith('.css'))return r.fulfill({contentType:'text/css',body:fs.readFileSync(path.join(dist,'leaflet.css'),'utf8')});if(u.includes('tile.openstreetmap.org'))return r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256"><rect width="256" height="256" fill="#607985"/></svg>'});return r.abort();};
 await page.route('https://**',intercept);
 const terrainFixture=route=>route.fulfill({contentType:'text/javascript',body:require('./timeline_terrain_fixture')});
 await page.route('**/timeline-terrain.js?*',terrainFixture);
 try{for(const width of [1366,390])for(const reduced of [false,true]){const record={width,reduced};try{
  await page.emulateMedia({reducedMotion:reduced?'reduce':'no-preference'});await page.setViewportSize({width,height:width===390?844:768});await page.goto(origin+'/timelines/latter-day-saint-church-history-timeline.html',{waitUntil:'load'});await page.waitForFunction(()=>window.HistoryTimelineMap&&window.__cameraMaps?.length===1&&window.TimelineWorkspace);await page.locator('#historyMapCanvas').scrollIntoViewIfNeeded();await page.waitForTimeout(1200);
  record.cases=await page.evaluate(async reduced=>{
   const map=window.__cameraMaps[0],data=HISTORY_LOCATIONS,api=HistoryTimeline,results=[];const pause=t=>new Promise(r=>setTimeout(r,t));
   const singles=data.events.filter(e=>e.places.length===1&&e.kind!=='region'&&e.kind!=='worldwide');const a=singles[0],p=data.places[a.places[0]],target=[p.lat,p.lng];
   async function test(name,index,start,startZoom,rapid){api.select(index);await pause(1100);map.stop();map.setView(start,startZoom,{animate:false});await pause(80);const beforeY=scrollY,frames=[];let active=true;function sample(){const c=map.getCenter();frames.push({lat:c.lat,lng:c.lng,z:map.getZoom()});if(active)requestAnimationFrame(sample);}sample();api.select(index);if(rapid){await pause(90);api.select(rapid.index);}await pause(1300);active=false;const actual=rapid||data.events[index],last=map.getCenter(),rect=map.getContainer().getBoundingClientRect();let expected=null;if(actual.kind==='worldwide')expected=[20,0];else if(actual.places.length===1){const q=data.places[actual.places[0]];expected=[q.lat,q.lng];}const points=actual.region?actual.region.bounds:actual.places.map(k=>[data.places[k].lat,data.places[k].lng]);results.push({name,index:actual.index,selected:api.selectedIndex,frames,center:{lat:last.lat,lng:last.lng},zoom:map.getZoom(),distance:expected?map.distance(last,expected):null,pixelError:expected?map.project(last,map.getZoom()).distanceTo(map.project(expected,map.getZoom())):null,boundsContained:points.every(q=>map.getBounds().contains(q)),beforeY,afterY:scrollY,rect:{width:rect.width,height:rect.height}});}
   await test('far',a.index,[0,0],3);await test('near',a.index,[p.lat+.05,p.lng],9);await test('near-diagonal',a.index,[p.lat+.05,p.lng+.05],9);await test('repeat',a.index,target,10);
   await test('multi-place',data.events.find(e=>e.places.length>1&&e.kind!=='region').index,[0,0],3);await test('region',data.events.find(e=>e.kind==='region').index,[0,0],3);await test('worldwide',data.events.find(e=>e.kind==='worldwide').index,target,10);
   const other=singles.find(e=>{const q=data.places[e.places[0]];return map.distance(target,[q.lat,q.lng])>500000;});await test('rapid-latest',other.index,[0,0],3,a);return results;
  },reduced);
  for(const c of record.cases){assert.equal(c.selected,c.index,c.name+' latest story');assert(Math.abs(c.afterY-c.beforeY)<2,c.name+' preserves document');if(c.pixelError!==null)assertCentered(c.pixelError);assert(c.boundsContained,c.name+' geographic extent');const unique=new Set(c.frames.map(f=>[f.lat.toFixed(6),f.lng.toFixed(6),f.z.toFixed(4)].join(','))).size;if(!reduced&&['far','near','near-diagonal','multi-place','region','worldwide','rapid-latest'].includes(c.name))assert(unique>3,c.name+' genuine intermediate camera frames');if(reduced||c.name==='repeat')assert(unique<=3,c.name+' no animated excursion');if(c.name==='near'||c.name==='near-diagonal')assert.equal(c.zoom,9);}
  await page.screenshot({path:path.join(out,'history-camera-'+width+'-'+(reduced?'reduced':'animated')+'.png'),animations:'disabled'});record.status='PASS';
 }catch(error){record.error=String(error);record.stack=error.stack;await page.screenshot({path:path.join(out,'history-camera-'+width+'-'+reduced+'-failure.png')}).catch(()=>{});}records.push(record);}}
 finally{await page.unroute('**/timeline-terrain.js?*',terrainFixture);await page.unroute('https://**',intercept);fs.writeFileSync(path.join(out,'history-camera.json'),JSON.stringify(records,null,2));}
 assert.equal(records.length,4);assert.deepEqual(records.filter(r=>r.error).map(r=>({width:r.width,reduced:r.reduced,error:r.error})),[]);return records;
};
