/* Hosted real Leaflet group selection; tile pixels are simulated, not provider evidence. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
function instrumentLeaflet(source){return source+'\n;window.__qaLeafletMaps=[];var make=L.map;L.map=function(){var m=make.apply(this,arguments);window.__qaLeafletMaps.push(m);return m;};';}
// Real Leaflet ends with a source-map line comment. The observer must start a new line.
const fixture={window:{}};require('node:vm').runInNewContext(instrumentLeaflet('var L={map:function(){return {identity:42};}};\n//# sourceMappingURL=leaflet.js.map'),fixture);assert.equal(fixture.L.map().identity,42);assert.equal(fixture.window.__qaLeafletMaps.length,1,'Map observer survives a trailing source-map comment');
module.exports=async function(page,origin,out){
 const records=[],dist=path.dirname(require.resolve('leaflet'));
 const intercept=async r=>{const u=r.request().url();if(u.includes('/leaflet@')&&u.endsWith('.js'))return r.fulfill({contentType:'text/javascript',body:instrumentLeaflet(fs.readFileSync(path.join(dist,'leaflet.js'),'utf8'))});if(u.includes('leaflet')&&u.endsWith('.css'))return r.fulfill({contentType:'text/css',body:fs.readFileSync(path.join(dist,'leaflet.css'),'utf8')});if(u.includes('tile.openstreetmap.org'))return r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256"><rect width="256" height="256" fill="#54717a"/></svg>'});return r.abort();};
 await page.route('https://**',intercept);
 const terrainFixture=route=>route.fulfill({contentType:'text/javascript',body:"window.FCTerrainLayer=function(){return L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19});};"});
 await page.route('**/timeline-terrain.js?*',terrainFixture);
 try{for(const [width,height,scale] of [[1366,720,1],[390,844,1],[320,900,2]])for(const kind of ['history','handcart','life','americas']){
  const route={history:'latter-day-saint-church-history-timeline',handcart:'willie-and-martin-handcart-map',life:'life-of-christ-journey-map',americas:'life-of-christ-journey-map'}[kind],record={kind,width,height,scale};
  try{
   await page.setViewportSize({width,height});await page.goto(origin+'/timelines/'+route+'.html',{waitUntil:'load'});await page.waitForFunction(()=>window.__qaLeafletMaps&&window.__qaLeafletMaps.length===1&&window.TimelineWorkspace);await page.locator('.leaflet-tile-loaded').first().waitFor();
   const enlarge=()=>page.evaluate(scale=>{if(scale===1)return;const nodes=[...document.body.querySelectorAll('*')];nodes.forEach(n=>{if(n.dataset.qaGroupScaled)n.style.fontSize=n.dataset.qaGroupOriginal;});const sizes=nodes.map(n=>parseFloat(getComputedStyle(n).fontSize));nodes.forEach((n,i)=>{if(!n.dataset.qaGroupScaled)n.dataset.qaGroupOriginal=n.style.fontSize;n.style.fontSize=sizes[i]*scale+'px';n.dataset.qaGroupScaled='true';});},scale);await enlarge();
   record.headerGeometry=await require('./timeline_header_geometry_qa')(page);
   record.creditGeometry=await require('./timeline_attribution_geometry_qa')(page,width);
   await page.locator('.leaflet-container').scrollIntoViewIfNeeded();
   record.initialMarkerGeometry=await require('./timeline_marker_geometry_qa')(page);
   const openFilters=async()=>{const d=page.locator('.timeline-filter-disclosure');if(!(await d.evaluate(n=>n.open)))await d.locator(':scope > summary').click();};
   const current=()=>page.evaluate(kind=>kind==='history'?window.HistoryTimeline.selectedIndex:kind==='handcart'?window.HandcartTimeline.current:window.LifeTimeline.current,kind);
   if(kind==='life'){
    const isolated=await page.evaluate(()=>{const i=LifeTimeline.stops.findIndex(s=>s.place==='Egypt');if(i<0)throw new Error('Egypt study stop missing');window.__qaLeafletMaps[0].setView([LifeTimeline.stops[i].lat,LifeTimeline.stops[i].lng],16,{animate:false});return i;});await page.waitForFunction(i=>LifeTimeline.mappedGroups.some(g=>g.length===1&&g[0]===i),isolated);record.singletonIndex=isolated;
    // Life's individual pins preserve ordinary journey controls.
    const marker=page.locator('.leaflet-marker-icon').filter({has:page.locator('.pin').filter({hasText:new RegExp('^'+(isolated+1)+'$')})}).first();await marker.click();assert.equal(await page.locator('.timeline-group-nav').count(),0);const before=await current();await page.locator('.timeline-event-navigation').getByRole('button',{name:'Next',exact:true}).click();assert.equal(await current(),(before+1)%(await page.evaluate(()=>window.LifeTimeline.stops.length)));await page.locator('.timeline-event-navigation').getByRole('button',{name:'Previous',exact:true}).click();assert.equal(await current(),before);record.ordinaryGlobalNavigation=true;
    await openFilters();await page.locator('#btnWorld').click();await page.waitForTimeout(900);await enlarge();await page.locator('.leaflet-container').scrollIntoViewIfNeeded();const cluster=await page.locator('.life-cluster-icon').evaluateAll(nodes=>nodes.map((n,i)=>{const r=n.querySelector('.handcart-cluster').getBoundingClientRect(),x=r.x+r.width/2,y=r.y+r.height/2,h=document.elementFromPoint(x,y);return {i,x,y,hit:h&&(h===n||n.contains(h))};}).find(n=>n.hit));assert(cluster,'World view exposes selectable grouped Life places');await page.mouse.click(cluster.x,cluster.y);const lifeChoices=page.locator('.timeline-place-choices button:not(.timeline-choices-back)'),lifeLabels=await lifeChoices.allTextContents(),lifeIndices=lifeLabels.map(t=>parseInt(t,10)-1);assert(lifeIndices.length>1);await lifeChoices.first().click();const lifeNav=page.locator('.timeline-group-nav');assert.equal(await current(),lifeIndices[0]);const lifeSequence=await page.evaluate(()=>TimelineNavigationAdapter.visibleIndices());await page.locator('.timeline-event-navigation').getByRole('button',{name:'Next',exact:true}).click();assert.equal(await current(),lifeSequence[lifeSequence.indexOf(lifeIndices[0])+1]);await page.evaluate(()=>window.__qaLeafletMaps[0].zoomIn());await page.waitForTimeout(350);await lifeNav.getByRole('button',{name:'Back to this pin\u2019s events',exact:true}).click();assert.deepEqual(await lifeChoices.allTextContents(),lifeLabels);record.lifeClusterIndices=lifeIndices;record.selectedGroupMarkerGeometry=await require('./timeline_marker_geometry_qa')(page);await page.screenshot({path:path.join(out,'pin-group-life-'+width+'-scale'+scale+'.png'),animations:'disabled'});
   }else if(kind==='americas'){
    const filter=async name=>{const disclosure=page.locator('.timeline-filter-disclosure');if(!(await disclosure.evaluate(n=>n.open)))await disclosure.locator(':scope > summary').click();await page.locator('#filters [data-filter="'+name+'"]').click();await enlarge();};
    await filter('americas');const diagram=page.locator('#internalMap'),picture=diagram.locator('img');await diagram.waitFor({state:'visible'});await picture.scrollIntoViewIfNeeded();await page.waitForFunction(()=>{const i=document.querySelector('#internalMap img');return i.complete&&i.naturalWidth===3072;});assert.equal(await page.locator('#map .pin').count(),0,'Americas has no Earth markers');assert.deepEqual(await page.evaluate(()=>LifeTimeline.stops.slice(29,31).map(s=>[s.lat,s.lng])),[[null,null],[null,null]]);
    const internalGeometry=await diagram.evaluate(n=>{const r=n.getBoundingClientRect(),frame=n.closest('[data-timeline-pane="map"]').getBoundingClientRect();return {diagram:{top:r.top,bottom:r.bottom},frame:{top:frame.top,bottom:frame.bottom},items:[...n.querySelectorAll('.internal-map-actions > *')].map(e=>{const b=e.getBoundingClientRect();return {text:e.textContent,top:b.top,bottom:b.bottom,height:b.height,clientHeight:e.clientHeight,scrollHeight:e.scrollHeight};})};});assert(internalGeometry.items.length===2);assert(internalGeometry.items.every(i=>i.scrollHeight<=i.clientHeight+1&&i.top>=internalGeometry.diagram.top-1&&i.bottom<=internalGeometry.diagram.bottom+1&&i.top>=internalGeometry.frame.top-1&&i.bottom<=internalGeometry.frame.bottom+1),'Internal map label and complete Bountiful button fit their visible map frame');assert(internalGeometry.items[1].height>=44);record.internalGeometry=internalGeometry;
    await page.locator('#bountifulEvents').click();const choices=page.locator('.timeline-place-choices button:not(.timeline-choices-back)'),labels=await choices.allTextContents();const expected=await page.evaluate(()=>[29,30].map(i=>(i+1)+'. '+LifeTimeline.stops[i].title));assert.deepEqual(labels,expected);await choices.first().click();await enlarge();const nav=page.locator('.timeline-group-nav');assert.equal(await current(),29);assert(await page.locator('.timeline-event-navigation').getByRole('button',{name:'Previous',exact:true}).isDisabled());await page.locator('.timeline-event-navigation').getByRole('button',{name:'Next',exact:true}).click();await enlarge();assert.equal(await current(),30);assert(await page.locator('.timeline-event-navigation').getByRole('button',{name:'Next',exact:true}).isDisabled());assert(await diagram.isVisible());await nav.getByRole('button',{name:'Back to this pin\u2019s events',exact:true}).click();assert.deepEqual(await choices.allTextContents(),expected);record.labels=labels;
    await page.screenshot({path:path.join(out,'pin-group-americas-'+width+'-scale'+scale+'.png'),animations:'disabled'});
    await openFilters();await page.locator('#btnWorld').click();assert(await diagram.isHidden());assert.deepEqual(await page.evaluate(()=>LifeTimeline.mappedGroups.flat().sort((a,b)=>a-b)),[...Array(38).keys()].filter(i=>i!==29&&i!==30),'Full journey represents each36 geographic indices once');assert.equal(await nav.count(),0);assert.equal(await page.locator('#map .pin').filter({hasText:/^(30|31)$/}).count(),0,'Unlocated events never acquire Earth markers');
    await page.waitForTimeout(900);await enlarge();await page.locator('.leaflet-container').scrollIntoViewIfNeeded();record.fullJourneyMarkerGeometry=await require('./timeline_marker_geometry_qa')(page);
    await filter('restoration');await page.locator('#timeline [data-stop-index="31"]').click();await enlarge();assert.equal(await current(),31);assert(await diagram.isHidden());assert.deepEqual(await page.evaluate(()=>LifeTimeline.mappedGroups.flat().sort((a,b)=>a-b)),[31,32,33,34,35,36,37]);assert(await page.evaluate(()=>LifeTimeline.mappedGroups.some(g=>g.includes(31))));assert((await page.locator('#detail').textContent()).includes(await page.evaluate(()=>LifeTimeline.stops[31].title)));const figure=page.locator('[data-timeline-image="31"]');await figure.scrollIntoViewIfNeeded();await page.waitForFunction(()=>{const i=document.querySelector('[data-timeline-image="31"] img');return i&&i.complete&&i.naturalWidth>0;});assert.equal(await figure.locator('img').getAttribute('src'),await page.evaluate(()=>TimelineImages.registry.life[31].src));record.diagramWidth=await picture.evaluate(i=>i.naturalWidth);record.restorationSelected=32;assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+3));
   }else{
    await page.evaluate(kind=>window.__qaLeafletMaps[0].setView(kind==='history'?[53.5,-2.7]:[42,-109],kind==='history'?5:4,{animate:false}),kind);
    await page.locator('.leaflet-container').scrollIntoViewIfNeeded();
    const selector=kind==='history'?'.history-map-icon':'.handcart-cluster-icon';
    const visibleChoice=()=>page.locator(selector).evaluateAll(nodes=>{const b=document.querySelector('.leaflet-container').getBoundingClientRect();return nodes.map((n,i)=>{const r=n.getBoundingClientRect(),count=parseInt(n.textContent,10),x=r.x+r.width/2,y=r.y+r.height/2,hit=document.elementFromPoint(x,y);return {i,count,x,y,receivesPointer:!!hit&&(hit===n||n.contains(hit))};}).filter(n=>n.count>1&&n.receivesPointer&&n.x>b.left+20&&n.x<b.right-20&&n.y>b.top+20&&n.y<b.bottom-20).sort((a,b)=>b.count-a.count)[0];});
    let choice=await visibleChoice();if(!choice){await page.evaluate(()=>{const m=window.__qaLeafletMaps[0];m.panBy([0,m.getSize().y*.3],{animate:false});});await page.waitForTimeout(100);choice=await visibleChoice();record.repositionedForMapControls=true;}assert(choice,'Visible multi-event map pin with an unobscured actual click target');record.clickedPin=choice;await page.mouse.click(choice.x,choice.y);
    const choices=page.locator('.timeline-place-choices button:not(.timeline-choices-back)');const labels=await choices.allTextContents();assert(labels.length>1);
    const indices=await page.evaluate(({kind,labels})=>labels.map(label=>kind==='history'?window.HistoryTimeline.events.findIndex(e=>label.endsWith(e.title)):parseInt(label,10)-1),{kind,labels});assert(indices.every(i=>i>=0));record.labels=labels;record.indices=indices;
    await choices.first().click();await enlarge();const nav=page.locator('.timeline-group-nav');assert.equal(await current(),indices[0]);
    const sequence=await page.evaluate(()=>TimelineNavigationAdapter.visibleIndices()),position=sequence.indexOf(indices[0]),eventNav=page.locator('.timeline-event-navigation');assert(position>=0);assert.equal(await eventNav.getByRole('button',{name:'Previous',exact:true}).isDisabled(),position===0);
    const outside=sequence.findIndex((i,p)=>p>position&&!indices.includes(i));const destination=outside>=0?outside:Math.min(position+1,sequence.length-1);
    for(let p=position+1;p<=destination;p++){await eventNav.getByRole('button',{name:'Next',exact:true}).click();await enlarge();assert.equal(await current(),sequence[p],'Next follows chronological filtered list, not pin membership');}
    assert.equal(await eventNav.getByRole('button',{name:'Next',exact:true}).isDisabled(),destination===sequence.length-1);if(destination>position){await eventNav.getByRole('button',{name:'Previous',exact:true}).click();await enlarge();assert.equal(await current(),sequence[destination-1]);}record.chronologicalSequence=sequence;record.steppedOutsidePin=outside>=0;
    await page.locator('.leaflet-control-zoom-in').click();await page.waitForTimeout(350);assert.equal(await nav.count(),1,'Map zoom preserves selected group');
    await nav.getByRole('button',{name:'Back to this pin\u2019s events',exact:true}).click();assert.deepEqual(await choices.allTextContents(),labels,'Back retains exact original pin group after zoom');await choices.last().click();await enlarge();assert.equal(await current(),indices.at(-1));
    const geometry=await nav.evaluate(n=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,buttons:[...n.querySelectorAll('button')].map(b=>{const r=b.getBoundingClientRect();return {height:r.height,left:r.left,right:r.right};})}));assert(geometry.scrollWidth<=geometry.width+3);assert(geometry.buttons.every(b=>b.height>=44&&b.left>=-1&&b.right<=geometry.width+1),'Group controls remain readable contained44px targets');record.geometry=geometry;
    await nav.scrollIntoViewIfNeeded();if(width<=900){await nav.evaluate(n=>{const header=document.querySelector('[data-focuschrist-header="standard"]').getBoundingClientRect(),dock=document.querySelector('.timeline-map-dock').getBoundingClientRect();window.scrollBy({top:n.getBoundingClientRect().top-header.height-dock.height-12,behavior:'instant'});});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const buffer=await nav.getByRole('button',{name:'Back to this pin\u2019s events',exact:true}).evaluate(n=>({top:n.getBoundingClientRect().top,dockBottom:document.querySelector('.timeline-map-dock').getBoundingClientRect().bottom}));assert(buffer.top>=buffer.dockBottom+10,'Back control begins below sticky map with reading buffer');record.backControlBuffer=buffer;}record.selectedGroupMarkerGeometry=await require('./timeline_marker_geometry_qa')(page);await page.screenshot({path:path.join(out,'pin-group-'+kind+'-'+width+'-scale'+scale+'.png'),animations:'disabled'});
    const disclosure=page.locator('.timeline-filter-disclosure');if(!(await disclosure.evaluate(n=>n.open)))await disclosure.locator(':scope > summary').click();if(kind==='history'){await page.locator('#search').fill('temple');}else await page.locator('[data-filter="willie"]').click();assert.equal(await nav.count(),0,'Filter clears old group');assert.equal(await page.locator('.timeline-place-choices').count(),0);record.filterCleared=true;
   }
   await enlarge();await page.locator('.leaflet-container').scrollIntoViewIfNeeded();record.finalMarkerGeometry=await require('./timeline_marker_geometry_qa')(page);
   record.status='PASS';
  }catch(error){record.error=String(error);record.stack=error.stack;await page.screenshot({path:path.join(out,'pin-group-'+kind+'-'+width+'-scale'+scale+'-failure.png'),animations:'disabled'}).catch(()=>{});}records.push(record);
 }}finally{await page.unroute('**/timeline-terrain.js?*',terrainFixture);await page.unroute('https://**',intercept);fs.writeFileSync(path.join(out,'pin-groups.json'),JSON.stringify({evidence:'Real pinned Leaflet markers; simulated tiles; not physical-device acceptance',records},null,2));}
 assert.equal(records.length,12);assert.deepEqual(records.filter(r=>r.error),[],'Every pin group and ordinary Life navigation case must pass');return records;
};
