/* Hosted-only mobile study containment; provider/network pixels are reviewed separately. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
module.exports=async function(page,origin,out){
 const records=[];
 for(const [width,height,scale] of [[390,844,1],[320,900,2],[844,390,1]])for(const route of ['timelines/willie-and-martin-handcart-map.html','timelines/life-of-christ-journey-map.html','timelines/latter-day-saint-church-history-timeline.html']){
  try{
   await page.setViewportSize({width,height});await page.goto(origin+'/'+route,{waitUntil:'load'});
   const enlarge=()=>page.evaluate(scale=>{if(scale===1)return;const nodes=[...document.body.querySelectorAll('*')];nodes.forEach(n=>{if(n.dataset.qaTextScaled==='true')n.style.fontSize=n.dataset.qaOriginalFontSize;});const sizes=nodes.map(n=>parseFloat(getComputedStyle(n).fontSize));nodes.forEach((n,i)=>{if(n.dataset.qaTextScaled!=='true')n.dataset.qaOriginalFontSize=n.style.fontSize;n.style.fontSize=sizes[i]*scale+'px';n.dataset.qaTextScaled='true';});},scale);await enlarge();
   const history=route.includes('church-history'),handcart=route.includes('handcart'),storyType=history?'timeline':'detail';
   const workspace=page.locator('[data-timeline-workspace]'),events=page.locator('[data-timeline-pane="events"]'),story=page.locator('[data-timeline-pane="'+storyType+'"]'),map=page.locator('[data-timeline-pane="map"]');
   await page.locator('a[href="#'+(history?'historyWorkspace':'journeyWorkspace')+'"]').click();
   await page.waitForFunction(()=>{const r=document.querySelector('[data-timeline-workspace]').getBoundingClientRect(),h=document.querySelector('[data-focuschrist-header="standard"]').getBoundingClientRect();return Math.abs(r.top-h.bottom-12)<=1;});
   const snapshot=()=>page.evaluate(storyType=>{const box=n=>{const r=n.getBoundingClientRect();return {top:r.top,bottom:r.bottom,height:r.height,left:r.left,right:r.right,scroll:n.scrollTop,scrollHeight:n.scrollHeight,clientHeight:n.clientHeight,display:getComputedStyle(n).display};};return {windowY:scrollY,width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,workspace:box(document.querySelector('[data-timeline-workspace]')),map:box(document.querySelector('[data-timeline-pane="map"]')),events:box(document.querySelector('[data-timeline-pane="events"]')),story:box(document.querySelector('[data-timeline-pane="'+storyType+'"]')),tabs:box(document.querySelector('.timeline-mobile-tabs'))};},storyType);
   let initial=await snapshot();assert(initial.scrollWidth<=width+3,'No document horizontal overflow');assert(initial.workspace.bottom<=height+1,'Study workspace fits below menu');assert(initial.events.height>=96,'Readable lower pane remains available');
   const toggle=page.locator('.timeline-map-toggle');if(height<560)assert.equal(await toggle.getAttribute('aria-expanded'),'false','Short screens begin with collapsed map');
   if(await toggle.getAttribute('aria-expanded')==='false')await toggle.click();
   initial=await snapshot();assert(initial.map.height>=(height<560?60:90),'Expanded map has usable height');assert(initial.map.bottom<=initial.tabs.top+1,'Map does not cover tabs');assert(initial.tabs.bottom<=initial.events.top+1,'Tabs do not cover reading pane');assert(initial.workspace.bottom<=height+1,'Expanded workspace remains contained');
   await events.evaluate(n=>n.scrollTop=0);const start=await snapshot();assert(start.events.scrollHeight>start.events.clientHeight+20,'Event list actually overflows');const b=await events.boundingBox();await page.mouse.move(b.x+b.width/2,b.y+Math.min(50,b.height/2));await page.mouse.wheel(0,150);await page.waitForFunction(()=>document.querySelector('[data-timeline-pane="events"]').scrollTop>10);const afterWheel=await snapshot();assert(Math.abs(afterWheel.windowY-start.windowY)<1,'Event wheel keeps document fixed');assert(Math.abs(afterWheel.map.top-start.map.top)<1&&afterWheel.map.scroll===start.map.scroll,'Event wheel keeps map fixed');
   await events.evaluate(n=>n.scrollTop=0);const selector=history?'#eventDirectory button':handcart?'.stop-card':'#timeline .card';const first=page.locator(selector).first();const expected=history?await first.getAttribute('data-event'):handcart?(await first.locator('h3').innerText()).trim():'The Annunciation to Mary';const beforeSelect=await snapshot();await first.click();assert.equal(await workspace.getAttribute('data-mobile-view'),'story');
   if(history)assert.equal(await page.locator('#'+expected+' .card-top').getAttribute('aria-expanded'),'true');else assert.equal((await page.locator(handcart?'#detail-title':'#dTitle').innerText()).trim(),expected);
   await enlarge();const selected=await snapshot();assert(Math.abs(selected.windowY-beforeSelect.windowY)<1,'Event selection keeps document fixed');assert(Math.abs(selected.map.top-beforeSelect.map.top)<1,'Selection keeps map fixed');assert.equal(selected.events.display,'none');assert.notEqual(selected.story.display,'none');assert(selected.story.bottom<=height+1,'Story is contained');
   // The selected full story must scroll inside its own reader when longer than the allotted area.
   let storyWheel=null;await story.evaluate(n=>n.scrollTop=0);let storyStart=await snapshot();if(storyStart.story.scrollHeight>storyStart.story.clientHeight+20){const r=await story.boundingBox();await page.mouse.move(r.x+r.width/2,r.y+Math.min(50,r.height/2));await page.mouse.wheel(0,150);await page.waitForFunction(type=>document.querySelector('[data-timeline-pane="'+type+'"]').scrollTop>10,storyType);storyWheel=await snapshot();assert(Math.abs(storyWheel.windowY-storyStart.windowY)<1&&Math.abs(storyWheel.map.top-storyStart.map.top)<1,'Story wheel leaves document and map fixed');}
   const expanded=await snapshot();await toggle.click();const collapsed=await snapshot();assert.equal(await toggle.getAttribute('aria-expanded'),'false');assert(collapsed.story.height>expanded.story.height+(height<560?55:70),'Collapsing map grants reading space');assert(collapsed.story.bottom<=height+1);await toggle.click();assert.equal(await toggle.getAttribute('aria-expanded'),'true');await page.locator('[data-study-view="events"]').click();assert(await events.isVisible());
   await page.screenshot({path:path.join(out,'mobile-study-'+width+'x'+height+'-scale'+scale+'-'+path.basename(route,'.html')+'.png'),animations:'disabled'});
   records.push({route,width,height,scale,initial,afterWheel,selected,storyWheel,collapsed,status:'PASS'});
  }catch(error){records.push({route,width,height,scale,error:String(error),stack:error.stack});await page.screenshot({path:path.join(out,'mobile-study-'+width+'x'+height+'-scale'+scale+'-'+path.basename(route,'.html')+'-failure.png'),animations:'disabled'}).catch(()=>{});}
 }
 fs.writeFileSync(path.join(out,'mobile-study.json'),JSON.stringify(records,null,2));assert.equal(records.length,9);assert.deepEqual(records.filter(r=>r.error),[],'Every mobile contained-study case must pass');return records;
};
