/* Hosted-browser geometry and independent scrolling checks for owner-requested timeline workspaces. */
const assert=require('node:assert/strict');
module.exports=async function(page,origin,out){
 const fs=require('node:fs'),path=require('node:path'),records=[];
 for(const [width,height,scale] of [[1366,720,1],[1920,1080,1],[1366,500,1],[1366,900,2]])for(const [route,types] of [
  ['timelines/willie-and-martin-handcart-map.html',['events','map','detail']],
  ['timelines/life-of-christ-journey-map.html',['events','map','detail']],
  ['timelines/latter-day-saint-church-history-timeline.html',['events','map','timeline']]
 ]){
  try{await page.setViewportSize({width,height});await page.goto(origin+'/'+route,{waitUntil:'load'});
  const enlarge=()=>page.evaluate(scale=>{if(scale===1)return;const nodes=[...document.body.querySelectorAll('*')];nodes.forEach(n=>{if(n.dataset.qaTextScaled==='true')n.style.fontSize=n.dataset.qaOriginalFontSize;});const sizes=nodes.map(n=>parseFloat(getComputedStyle(n).fontSize));nodes.forEach((n,i)=>{if(n.dataset.qaTextScaled!=='true')n.dataset.qaOriginalFontSize=n.style.fontSize;n.style.fontSize=sizes[i]*scale+'px';n.dataset.qaTextScaled='true';});},scale);await enlarge();
  const workspace=page.locator('[data-timeline-workspace]');assert.equal(await workspace.count(),1,route+' one bounded workspace');
  const entry=page.locator(types.includes('timeline')?'a[href="#historyWorkspace"]':'a[href="#journeyWorkspace"]');await entry.click();await page.waitForFunction(()=>{const w=document.querySelector('[data-timeline-workspace]').getBoundingClientRect(),h=document.querySelector('[data-focuschrist-header="standard"]').getBoundingClientRect();return Math.abs(w.top-h.bottom-12)<=1&&w.bottom<=innerHeight+1;});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>requestAnimationFrame(r)))));const entryGeometry=await workspace.evaluate(n=>{const r=n.getBoundingClientRect();return {top:r.top,bottom:r.bottom,windowY:scrollY,headerBottom:document.querySelector('[data-focuschrist-header="standard"]').getBoundingClientRect().bottom};});assert(Math.abs(entryGeometry.top-entryGeometry.headerBottom-12)<=1&&entryGeometry.bottom<=height+1,'Explore entry stays aligned after layout frames');
  if(types.includes('detail')){const cards=page.locator(route.includes('handcart')?'.stop-card':'#timeline .card');let longest={index:0,length:0};for(let i=0;i<await cards.count();i++){await cards.nth(i).click();const length=(await page.locator('[data-timeline-pane="detail"]').innerText()).length;if(length>longest.length)longest={index:i,length};}await cards.nth(longest.index).click();}
  await enlarge();await workspace.evaluate(n=>n.scrollIntoView({block:'start',behavior:'instant'}));
  await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  const snapshot=()=>page.evaluate(types=>{const box=n=>{const r=n.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom,right:r.right};};return {windowY:scrollY,viewport:innerHeight,header:box(document.querySelector('nav[data-focuschrist-header="standard"]')),controls:document.querySelector('.controls')?box(document.querySelector('.controls')):null,panes:types.map(type=>{const n=document.querySelector('[data-timeline-pane="'+type+'"]');return {type,...box(n),scrollTop:n.scrollTop,scrollHeight:n.scrollHeight,clientHeight:n.clientHeight,overflow:getComputedStyle(n).overflowY};})};},types);
  await page.locator('[data-timeline-pane="events"]').evaluate(n=>n.scrollTop=0);
  const initial=await snapshot();if(types.includes('timeline')){assert.equal(await page.locator('#historyDirectory').evaluate(n=>getComputedStyle(n).overflowY),'visible','Directory wrapper must not add a redundant clipping ancestor');assert.equal(await page.locator('#eventDirectory').evaluate(n=>getComputedStyle(n).overflowY),'auto','Actual event pane retains scroll containment');}
  for(let i=0;i<initial.panes.length;i++){const pane=initial.panes[i];assert(pane.height>=(height===500?120:200),route+' usable '+pane.type+' height');assert(pane.y>=initial.header.bottom-1&&(types.includes('timeline')||!initial.controls||pane.y>=initial.controls.bottom-1),route+' '+pane.type+' below menu and filters');assert(pane.bottom<=height+1,route+' '+pane.type+' bounded by viewport');if(i)assert(pane.x>=initial.panes[i-1].right-1,route+' left-to-right pane order');}
  const events=page.locator('[data-timeline-pane="events"]');assert(initial.panes[0].scrollHeight>initial.panes[0].clientHeight+20,route+' event directory actually scrolls');
  const bounds=await events.boundingBox();await page.mouse.move(bounds.x+bounds.width/2,bounds.y+Math.min(80,bounds.height/2));await page.mouse.wheel(0,250);
  await page.waitForFunction(()=>document.querySelector('[data-timeline-pane="events"]').scrollTop>10);
  const after=await snapshot();assert(Math.abs(after.windowY-initial.windowY)<1,route+' event wheel leaves document fixed');for(let i=1;i<after.panes.length;i++){assert(Math.abs(after.panes[i].y-initial.panes[i].y)<1,route+' event wheel leaves sibling geometry fixed');assert.equal(after.panes[i].scrollTop,initial.panes[i].scrollTop,route+' event wheel leaves sibling scroll fixed');}
  let detailAfter=null;if(types.includes('detail')){const detail=after.panes.find(p=>p.type==='detail');if(height===500)assert(detail.scrollHeight>detail.clientHeight+20,route+' long story has independent overflow');if(detail.scrollHeight>detail.clientHeight+20){const pane=page.locator('[data-timeline-pane="detail"]');await pane.evaluate(n=>n.scrollTop=0);const b=await pane.boundingBox(),before=await snapshot();await page.mouse.move(b.x+b.width/2,b.y+60);await page.mouse.wheel(0,200);await page.waitForFunction(()=>document.querySelector('[data-timeline-pane="detail"]').scrollTop>10);detailAfter=await snapshot();assert(Math.abs(detailAfter.windowY-before.windowY)<1,'Detail wheel leaves document fixed');for(const kind of ['events','map'])assert.equal(detailAfter.panes.find(p=>p.type===kind).scrollTop,before.panes.find(p=>p.type===kind).scrollTop,'Detail wheel leaves '+kind+' fixed');}}
  let historySelection=null;if(types.includes('timeline')){const visibleIndex=await page.locator('#eventDirectory button').evaluateAll(nodes=>{const p=nodes[0].parentElement.getBoundingClientRect();return nodes.map((n,i)=>({i,r:n.getBoundingClientRect()})).filter(x=>x.r.top>=p.top&&x.r.bottom<=p.bottom).at(-1).i;});const button=page.locator('#eventDirectory button').nth(visibleIndex);const before=await snapshot(),target=await button.getAttribute('data-event');await button.click();historySelection=await snapshot();assert(Math.abs(historySelection.windowY-before.windowY)<1,'History selection leaves document fixed');assert.equal(historySelection.panes[0].scrollTop,before.panes[0].scrollTop,'History selection leaves directory scroll fixed');assert.equal(await page.locator('#'+target+' .card-top').getAttribute('aria-expanded'),'true','Directory opens exact event inline');assert(historySelection.panes.find(p=>p.type==='timeline').scrollTop>0,'Directory moves only timeline reader');const lines=await page.locator('.era-block').evaluateAll(eras=>eras.map(e=>{const intro=e.querySelector('.era-head').getBoundingClientRect(),events=e.querySelector('.era-events'),r=events.getBoundingClientRect(),top=parseFloat(getComputedStyle(events,'::before').top);return {introBottom:intro.bottom,lineTop:r.top+top};}));assert(lines.every(l=>l.lineTop>=l.introBottom),'Each gold line starts after era introduction');const reader=page.locator('[data-timeline-pane="timeline"]');await reader.evaluate(n=>n.scrollTop=0);const b=await reader.boundingBox(),start=await snapshot();await page.mouse.move(b.x+b.width/2,b.y+80);await page.mouse.wheel(0,250);await page.waitForFunction(()=>document.querySelector('[data-timeline-pane="timeline"]').scrollTop>10);const end=await snapshot();assert(Math.abs(end.windowY-start.windowY)<1&&end.panes[0].scrollTop===start.panes[0].scrollTop,'Timeline wheel leaves document and directory fixed');}
  records.push({route,width,height,scale,entryGeometry,initial,after,detailAfter,historySelection,status:'PASS'});await page.screenshot({path:path.join(out,'panes-'+width+'x'+height+'-scale'+scale+'-'+path.basename(route,'.html')+'.png'),animations:'disabled'});
  }catch(error){records.push({route,width,height,scale,error:String(error),stack:error.stack});await page.screenshot({path:path.join(out,'panes-'+width+'x'+height+'-scale'+scale+'-'+path.basename(route,'.html')+'-failure.png'),animations:'disabled'}).catch(()=>{});}
 }
 fs.writeFileSync(path.join(out,'independent-panes.json'),JSON.stringify(records,null,2));assert.equal(records.length,12);assert.deepEqual(records.filter(r=>r.error),[],'All independent-pane profiles must pass');return records;
};
