/* Real Leaflet 1.9.4 interaction handlers with explicitly simulated tile pixels. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
module.exports=async function(page,origin,out){
 const records=[],dist=path.dirname(require.resolve('leaflet')),cdp=await page.context().newCDPSession(page);
 const intercept=async route=>{const url=route.request().url();if(/leaflet(?:@|\/|\.)/.test(url)&&url.endsWith('.js'))return route.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(dist,'leaflet.js'),'utf8')+'\n;window.__qaLeafletMaps=[];var originalQaMap=L.map;L.map=function(){var m=originalQaMap.apply(this,arguments);window.__qaLeafletMaps.push(m);return m;};'});if(url.includes('leaflet')&&url.endsWith('.css'))return route.fulfill({contentType:'text/css',body:fs.readFileSync(path.join(dist,'leaflet.css'),'utf8')});if(url.includes('tile.openstreetmap.org'))return route.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256"><rect width="256" height="256" fill="#607985"/><path d="M0 128H256M128 0V256" stroke="#a0b3b6"/></svg>'});return route.abort();};
 await page.route('https://**',intercept);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:1});
 async function swipe(x,y,dx,dy){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=12;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx*i/12,y:y+dy*i/12}]});await page.waitForTimeout(25);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(450);}
 const state=()=>page.evaluate(()=>{const m=window.__qaLeafletMaps[0],c=m.getCenter();return {y:scrollY,lat:c.lat,lng:c.lng,zoom:m.getZoom(),drag:m.dragging.enabled(),wheel:m.scrollWheelZoom.enabled()};});
 const settle=()=>page.waitForFunction(()=>{const m=window.__qaLeafletMaps[0],c=m.getCenter(),r=m.getContainer().getBoundingClientRect(),key=[c.lat,c.lng,m.getZoom(),r.width,r.height].join('|');if(window.__qaStableMapKey!==key||m._animatingZoom||m._panAnim&&m._panAnim._inProgress){window.__qaStableMapKey=key;window.__qaStableMapSince=performance.now();return false;}return performance.now()-window.__qaStableMapSince>300;});
 try{for(const route of ['willie-and-martin-handcart-map','life-of-christ-journey-map','latter-day-saint-church-history-timeline']){const evidence={};try{
  await page.setViewportSize({width:390,height:844});await page.goto(origin+'/timelines/'+route+'.html',{waitUntil:'load'});await page.waitForFunction(()=>window.__qaLeafletMaps&&window.__qaLeafletMaps.length===1);await page.locator('.leaflet-tile-loaded').first().waitFor();
  const map=page.locator('.leaflet-container');await map.scrollIntoViewIfNeeded();let b=await map.boundingBox();await settle();b=await map.boundingBox();const passive=evidence.passive=await state();assert.equal(passive.drag,false);assert.equal(passive.wheel,false);await swipe(b.x+b.width*.65,b.y+b.height*.8,0,-75);const scrolled=evidence.scrolled=await state();assert(scrolled.y>passive.y+15,'Passive map finger swipe advances document');assert(Math.abs(scrolled.lat-passive.lat)+Math.abs(scrolled.lng-passive.lng)<.00001,'Passive swipe does not pan map');
  await page.locator('.timeline-map-interact').click();b=await map.boundingBox();const active=evidence.active=await state();assert.equal(active.drag,true);await swipe(b.x+b.width*.5,b.y+b.height*.5,65,-35);const panned=evidence.panned=await state();assert(Math.abs(panned.lng-active.lng)+Math.abs(panned.lat-active.lat)>.001,'Explicit interaction pans actual Leaflet map');assert(Math.abs(panned.y-active.y)<2,'Active map pan preserves document position');
  const beforeZoom=panned.zoom;await page.locator('.leaflet-control-zoom-in').click();await page.waitForFunction(z=>window.__qaLeafletMaps[0].getZoom()>z,beforeZoom);await settle();await page.locator('.timeline-map-interact').click();const done=evidence.done=await state();assert.equal(done.drag,false);assert.equal(done.wheel,false);b=await map.boundingBox();await swipe(b.x+b.width*.65,b.y+b.height*.8,0,-75);const resumed=evidence.resumed=await state();assert(resumed.y>done.y+15,'Done restores document swipe over map');assert(Math.abs(resumed.lat-done.lat)+Math.abs(resumed.lng-done.lng)<.00001,'Done swipe does not pan map');
  await page.screenshot({path:path.join(out,'leaflet-touch-'+route+'.png'),animations:'disabled'});records.push({route,status:'PASS',passive,scrolled,active,panned,done,resumed,evidence:'Real pinned Leaflet handlers; simulated tile pixels; CDP finger input, not physical Android.'});
 }catch(error){records.push({route,error:String(error),stack:error.stack,evidence});await page.screenshot({path:path.join(out,'leaflet-touch-'+route+'-failure.png'),animations:'disabled'}).catch(()=>{});}}
 }finally{await page.unroute('https://**',intercept);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:false});await cdp.detach();fs.writeFileSync(path.join(out,'leaflet-touch.json'),JSON.stringify(records,null,2));}
 assert.equal(records.length,3);assert.deepEqual(records.filter(r=>r.error),[],'Every real-Leaflet touch case must pass');return records;
};
