/* Focused opening evidence; actual artwork composition still requires independent pixel review. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
module.exports=async function(page,origin,out){
 const records=[];
 for(const [width,height,scale] of [[1366,768,1],[1920,900,1],[1366,500,1],[390,844,1],[320,740,1],[320,900,2]])for(const kind of ['history','life','handcart']){
  const r={kind,width,height,scale};try{
   await page.setViewportSize({width,height});await page.goto(origin+'/timelines/'+({life:'life-of-christ-journey-map',history:'latter-day-saint-church-history-timeline',handcart:'willie-and-martin-handcart-map'}[kind])+'.html',{waitUntil:'load'});
   await page.evaluate(()=>document.fonts.ready);if(scale!==1)await page.evaluate(scale=>{const nodes=[...document.body.querySelectorAll('*')],sizes=nodes.map(n=>parseFloat(getComputedStyle(n).fontSize));nodes.forEach((n,i)=>n.style.fontSize=sizes[i]*scale+'px');},scale);await page.evaluate(()=>window.dispatchEvent(new Event('resize')));await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.evaluate(()=>scrollTo(0,0));
   r.header=await require('./timeline_header_geometry_qa')(page);
   assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+3),'Opening has no horizontal overflow');
   {
    const hero=page.locator('.fc-visual-hero');assert.equal(await hero.count(),1,'Each corrected page has one real shared image hero');const img=hero.locator('img');await img.evaluate(i=>i.decode());r.image=await img.evaluate(i=>({src:i.currentSrc,width:i.naturalWidth,height:i.naturalHeight,alt:i.alt}));assert(r.image.width>500&&r.image.height>200&&r.image.alt.length>20,'Actual described artwork loaded');if(kind==='life'){assert(r.image.src.endsWith(width<=700?'assets/heroes/topics/jesus-mobile.webp':'assets/heroes/topics/jesus-desktop.webp'),'Approved existing Life artwork rendition');assert((await hero.getAttribute('href')).endsWith('answers/jesus-christ-latter-day-saint-beliefs.html#nested-page-title'),'Reference links to owning study');}
    if(kind==='handcart'){assert(r.image.src.endsWith('assets/heroes/pioneers.webp'));assert((await hero.getAttribute('href')).endsWith('pioneers.html#pioneer-page-title'));}
    const reference=await page.context().newPage();try{await reference.setViewportSize({width,height});await reference.goto(origin+'/birth-of-christ.html',{waitUntil:'load'});await reference.evaluate(()=>document.fonts.ready);await reference.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const expected=await reference.locator('.fc-visual-hero').boundingBox(),actual=await hero.boundingBox();r.frame={expected,actual};assert(Math.abs(expected.width-actual.width)<=1&&Math.abs(expected.height-actual.height)<=1,'Corrected page uses approved Birth shared hero frame');if(width===390)await reference.screenshot({path:path.join(out,'opening-reference-birth-390.png'),animations:'disabled'});}finally{await reference.close();}
    const clearance=await hero.evaluate(n=>({top:n.getBoundingClientRect().top,headerBottom:document.querySelector('[data-focuschrist-header="standard"]').getBoundingClientRect().bottom}));assert(clearance.top>=clearance.headerBottom-1,'Header cannot cover opening artwork');r.clearance=clearance;
   }
   if(kind==='history'){
    assert(r.image.src.endsWith('assets/timelines/church-history-grove.webp'));assert((await page.locator('.fc-visual-hero').getAttribute('href')).endsWith('church-history.html#history-first-vision-title'));
    r.kicker=await page.locator('.fc-page-intro .kicker').evaluate(n=>{const c=getComputedStyle(n);return {color:c.color,background:c.backgroundColor,text:n.textContent};});const rgb=s=>s.match(/[\d.]+/g).map(Number),fg=rgb(r.kicker.color),bg=rgb(r.kicker.background);assert(bg.length===3||bg[3]===1,'Kicker uses explicit opaque contrast surface');const lum=c=>c.slice(0,3).map(x=>x/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4).reduce((a,x,i)=>a+x*[.2126,.7152,.0722][i],0);r.contrast=(Math.max(lum(fg),lum(bg))+.05)/(Math.min(lum(fg),lum(bg))+.05);assert(r.contrast>=4.5,'History kicker has readable normal-text contrast');
   }
   r.controls=await page.locator('.hero a,.fc-page-intro a').evaluateAll(nodes=>nodes.filter(n=>n.getClientRects().length).map(n=>{const b=n.getBoundingClientRect();return {label:n.textContent,top:b.top,bottom:b.bottom,height:b.height,width:b.width,scroll:n.scrollHeight,client:n.clientHeight,left:b.left,right:b.right};}));assert(r.controls.every(c=>c.height>=44&&c.scroll<=c.client+1&&c.left>=-1&&c.right<=width+1),'Opening controls have complete labels and44px height');if(scale===1&&height!==500){assert(r.controls.length>0);assert(r.controls.every(c=>c.top>=0&&c.bottom<=height-8),'All normal opening navigation pills and Continue stay within first viewport');const cue=page.locator('.fc-page-intro .timeline-opening-continue');assert.equal(await cue.count(),1,'Shared Continue invitation exists');assert(await cue.isVisible(),'Shared Continue is visibly available');const target=await cue.getAttribute('href');assert(target&&target.startsWith('#'));assert.equal(await page.locator(target).count(),1,'Continue reaches an actual following section');r.continueTarget=target;const overview=await page.locator(target).boundingBox();assert(overview&&overview.y>=height-1,'Following overview begins after normal opening viewport');r.overviewTop=overview.y;}
   await page.screenshot({path:path.join(out,'opening-'+kind+'-'+width+'x'+height+'-scale'+scale+'.png'),animations:'disabled'});
   if(kind==='history'){const sources=page.locator('section.sources');await sources.scrollIntoViewIfNeeded();r.sources=await sources.evaluate(n=>{const c=getComputedStyle(n);return {background:c.backgroundColor,gradient:c.backgroundImage,border:c.borderTopColor,text:[...n.querySelectorAll('h2,p,li,a')].map(e=>({tag:e.tagName,color:getComputedStyle(e).color,text:e.textContent})),scroll:n.scrollWidth,client:n.clientWidth};});assert(r.sources.gradient!=='none','Sources uses shared green/teal panel gradient');const rgb=s=>s.match(/[\d.]+/g).map(Number),lum=c=>c.slice(0,3).map(x=>x/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4).reduce((a,x,i)=>a+x*[.2126,.7152,.0722][i],0),colors=r.sources.gradient.slice(r.sources.gradient.lastIndexOf('linear-gradient(')).match(/rgba?\([^)]+\)/g)||[];assert(colors.length>=2);for(const text of r.sources.text)for(const color of colors){const a=lum(rgb(text.color)),b=lum(rgb(color));assert((Math.max(a,b)+.05)/(Math.min(a,b)+.05)>=4.5,'Readable sources text/links against each panel gradient endpoint');}assert(r.sources.scroll<=r.sources.client+1,'Sources content stays within panel');await sources.screenshot({path:path.join(out,'sources-history-'+width+'x'+height+'-scale'+scale+'.png'),animations:'disabled'});}
   r.status='PASS';
  }catch(e){r.error=String(e);r.stack=e.stack;await page.screenshot({path:path.join(out,'opening-'+kind+'-'+width+'x'+height+'-failure.png'),animations:'disabled'}).catch(()=>{});}records.push(r);
 }
 fs.writeFileSync(path.join(out,'timeline-openings.json'),JSON.stringify(records,null,2));assert.equal(records.length,18);assert.deepEqual(records.filter(r=>r.error),[],'All changed opening profiles must pass');return records;
};
