/* Hosted touch input plus document-flow checks. Actual provider/Android acceptance remains separate. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
module.exports=async function(page,origin,out){
 const records=[],cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:1});
 async function swipe(x,y,endY){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=10;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:y+(endY-y)*i/10}]});await page.waitForTimeout(20);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(250);}
 for(const [width,height,scale] of [[390,844,1],[320,900,2],[844,390,1]])for(const route of ['timelines/willie-and-martin-handcart-map.html','timelines/life-of-christ-journey-map.html','timelines/latter-day-saint-church-history-timeline.html']){
  try{
   await page.setViewportSize({width,height});await page.goto(origin+'/'+route,{waitUntil:'load'});
   const enlarge=()=>page.evaluate(scale=>{if(scale===1)return;const nodes=[...document.body.querySelectorAll('*')];nodes.forEach(n=>{if(n.dataset.qaTextScaled==='true')n.style.fontSize=n.dataset.qaOriginalFontSize;});const sizes=nodes.map(n=>parseFloat(getComputedStyle(n).fontSize));nodes.forEach((n,i)=>{if(n.dataset.qaTextScaled!=='true')n.dataset.qaOriginalFontSize=n.style.fontSize;n.style.fontSize=sizes[i]*scale+'px';n.dataset.qaTextScaled='true';});},scale);await enlarge();
   const history=route.includes('church-history'),handcart=route.includes('handcart'),type=history?'timeline':'detail';const workspace=page.locator('[data-timeline-workspace]'),events=page.locator('[data-timeline-pane="events"]');
   assert(await workspace.evaluate(n=>n.classList.contains('timeline-mobile')));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+3),'No horizontal document overflow');
   const opening=await page.locator('.wrap>.hero').evaluate(n=>{const r=n.getBoundingClientRect();return {left:r.left,right:r.right,width:document.documentElement.clientWidth};});assert(opening.left>=-1&&opening.right<=opening.width+1,'Opening hero stays within document boundary');
   const ordinaryStart=await page.evaluate(()=>scrollY);await swipe(width/2,height*.78,height*.30);assert(await page.evaluate(start=>scrollY>start+20,ordinaryStart),'Ordinary finger swipe scrolls page without Explore');
   const flow=await events.evaluate(n=>({height:n.clientHeight,scrollHeight:n.scrollHeight,overflow:getComputedStyle(n).overflowY}));assert.equal(flow.overflow,'visible','Events have no private mobile scrollbar');assert(flow.scrollHeight<=flow.height+2,'Events expand to their full content');
   // Position a target after proving ordinary entry; then exercise real touch over it.
   const dock=page.locator('.timeline-map-dock');await dock.scrollIntoViewIfNeeded();const toggle=page.locator('.timeline-map-toggle');if(await toggle.getAttribute('aria-expanded')==='false')await toggle.click();
   const map=page.locator('[data-timeline-pane="map"]');const frame=await map.evaluate(n=>({radius:parseFloat(getComputedStyle(n).borderTopLeftRadius),overflow:getComputedStyle(n).overflow}));assert(frame.radius>=14&&frame.overflow==='hidden','Compact map preserves rounded contained frame');const gestureTarget=(await map.isVisible()&&(await map.boundingBox()).height>=40)?'map-pane':'fallback-notes';const gestureArea=gestureTarget==='map-pane'?map:page.locator('.timeline-map-notes');await gestureArea.scrollIntoViewIfNeeded();const b=await gestureArea.boundingBox(),header=await page.locator('[data-focuschrist-header="standard"]').boundingBox();const startY=Math.min(height-25,b.y+b.height-15),endY=Math.max(header.y+header.height+12,startY-100);assert(startY-endY>=20,'Map has exposed touch area');const beforeMapSwipe=await page.evaluate(()=>scrollY);await swipe(Math.max(25,Math.min(width-25,b.x+b.width/2)),startY,endY);assert(await page.evaluate(start=>scrollY>start+10,beforeMapSwipe),'Default map-area swipe scrolls document');
   await page.locator('[data-study-view="events"]').click();const selector=history?'#eventDirectory button':handcart?'.stop-card':'#timeline .card';const first=page.locator(selector).first();await first.click();await enlarge();await page.waitForTimeout(100);assert.equal(await workspace.getAttribute('data-mobile-view'),'story');
   if(history)assert.equal(await page.locator('#history-event-0 .card-top').getAttribute('aria-expanded'),'true');else assert.equal((await page.locator(handcart?'#detail-title':'#dTitle').innerText()).trim(),handcart?'Liverpool, England':'The Annunciation to Mary');
   const reader=page.locator('[data-timeline-pane="'+type+'"]'),reading=await reader.evaluate(n=>({height:n.clientHeight,scrollHeight:n.scrollHeight,overflow:getComputedStyle(n).overflowY}));assert.equal(reading.overflow,'visible','Story uses document flow');assert(reading.scrollHeight<=reading.height+2,'Story copy and image are not clipped to a viewport');const beforeStorySwipe=await page.evaluate(()=>scrollY);await swipe(width/2,height*.82,height*.4);assert(await page.evaluate(start=>scrollY>start+10,beforeStorySwipe),'Story finger swipe advances document');
   // Every page must be able to leave the study and reach its normal footer.
   await page.evaluate(()=>window.scrollTo(0,document.documentElement.scrollHeight-innerHeight-120));await swipe(width/2,height*.8,height*.35);assert(await page.evaluate(()=>scrollY+innerHeight>=document.documentElement.scrollHeight-5),'Footer/end reachable with touch');const bottom=await page.evaluate(()=>scrollY);await swipe(width/2,height*.35,height*.8);assert(await page.evaluate(y=>scrollY<y-10,bottom),'Reverse touch leaves page end');
   await page.locator('[data-study-view="events"]').click();await page.locator('.timeline-filter-disclosure>summary').click();assert(await page.locator('.timeline-filter-disclosure').evaluate(n=>n.open),'Filters open in ordinary flow');const controls=await page.locator('.controls').evaluate(n=>getComputedStyle(n).overflowY);assert.equal(controls,'visible','Filters do not trap touch in nested scrollbar');
   await page.locator('.timeline-filter-disclosure>summary').click();if(await toggle.getAttribute('aria-expanded')==='true')await toggle.click();assert.equal(await map.isVisible(),false,'Collapse releases map space');await toggle.click();
   await dock.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'mobile-study-'+width+'x'+height+'-scale'+scale+'-'+path.basename(route,'.html')+'.png'),animations:'disabled'});
   records.push({route,width,height,scale,opening,frame,ordinaryStart,beforeMapSwipe,beforeStorySwipe,events:flow,story:reading,touchInput:true,gestureTarget,providerLoaded:await page.locator('.leaflet-tile-loaded').count()>0,naturalDocumentFlow:true,status:'PASS'});
  }catch(error){records.push({route,width,height,scale,error:String(error),stack:error.stack});await page.screenshot({path:path.join(out,'mobile-study-'+width+'x'+height+'-scale'+scale+'-'+path.basename(route,'.html')+'-failure.png'),animations:'disabled'}).catch(()=>{});}
 }
 await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:false});await cdp.detach();fs.writeFileSync(path.join(out,'mobile-study.json'),JSON.stringify(records,null,2));assert.equal(records.length,9);assert.deepEqual(records.filter(r=>r.error),[],'Every mobile natural-flow/touch case must pass');return records;
};
