/* Hosted real Leaflet group selection; tile pixels are simulated, not provider evidence. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
module.exports=async function(page,origin,out){
 const records=[],dist=path.dirname(require.resolve('leaflet'));
 const intercept=async r=>{const u=r.request().url();if(u.includes('leaflet')&&u.endsWith('.js'))return r.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(dist,'leaflet.js'),'utf8')+';window.__qaLeafletMaps=[];var make=L.map;L.map=function(){var m=make.apply(this,arguments);window.__qaLeafletMaps.push(m);return m;};'});if(u.includes('leaflet')&&u.endsWith('.css'))return r.fulfill({contentType:'text/css',body:fs.readFileSync(path.join(dist,'leaflet.css'),'utf8')});if(u.includes('tile.openstreetmap.org'))return r.fulfill({contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256"><rect width="256" height="256" fill="#54717a"/></svg>'});return r.abort();};
 await page.route('https://**',intercept);
 try{for(const [width,height,scale] of [[1366,720,1],[390,844,1],[320,900,2]])for(const kind of ['history','handcart','life','americas']){
  const route={history:'latter-day-saint-church-history-timeline',handcart:'willie-and-martin-handcart-map',life:'life-of-christ-journey-map',americas:'life-of-christ-journey-map'}[kind],record={kind,width,height,scale};
  try{
   await page.setViewportSize({width,height});await page.goto(origin+'/timelines/'+route+'.html',{waitUntil:'load'});await page.waitForFunction(()=>window.__qaLeafletMaps&&window.__qaLeafletMaps.length===1&&window.TimelineWorkspace);await page.locator('.leaflet-tile-loaded').first().waitFor();
   const enlarge=()=>page.evaluate(scale=>{if(scale===1)return;const nodes=[...document.body.querySelectorAll('*')];nodes.forEach(n=>{if(n.dataset.qaGroupScaled)n.style.fontSize=n.dataset.qaGroupOriginal;});const sizes=nodes.map(n=>parseFloat(getComputedStyle(n).fontSize));nodes.forEach((n,i)=>{if(!n.dataset.qaGroupScaled)n.dataset.qaGroupOriginal=n.style.fontSize;n.style.fontSize=sizes[i]*scale+'px';n.dataset.qaGroupScaled='true';});},scale);await enlarge();
   const current=()=>page.evaluate(kind=>kind==='history'?window.HistoryTimeline.selectedIndex:kind==='handcart'?window.HandcartTimeline.current:window.LifeTimeline.current,kind);
   if(kind==='life'){
    await page.evaluate(()=>window.__qaLeafletMaps[0].setView([32.7,35.3],7,{animate:false}));
    // Life's individual pins preserve ordinary journey controls.
    const marker=page.locator('.leaflet-marker-icon').first();await marker.click();assert.equal(await page.locator('.timeline-group-nav').count(),0);const before=await current();await page.locator('#nextBtn').click();assert.equal(await current(),(before+1)%(await page.evaluate(()=>window.LifeTimeline.stops.length)));await page.locator('#prevBtn').click();assert.equal(await current(),before);record.ordinaryGlobalNavigation=true;
   }else if(kind==='americas'){
    const filter=async name=>{const disclosure=page.locator('.timeline-filter-disclosure');if(!(await disclosure.evaluate(n=>n.open)))await disclosure.locator(':scope > summary').click();await page.locator('#filters [data-filter="'+name+'"]').click();await enlarge();};
    await filter('americas');const diagram=page.locator('#internalMap'),picture=diagram.locator('img');await diagram.waitFor({state:'visible'});await picture.scrollIntoViewIfNeeded();await page.waitForFunction(()=>{const i=document.querySelector('#internalMap img');return i.complete&&i.naturalWidth===3072;});assert.equal(await page.locator('#map .pin').count(),0,'Americas has no Earth markers');assert.deepEqual(await page.evaluate(()=>LifeTimeline.stops.slice(29,31).map(s=>[s.lat,s.lng])),[[null,null],[null,null]]);
    await page.locator('#bountifulEvents').click();const choices=page.locator('.timeline-place-choices button:not(.timeline-choices-back)'),labels=await choices.allTextContents();const expected=await page.evaluate(()=>[29,30].map(i=>(i+1)+'. '+LifeTimeline.stops[i].title));assert.deepEqual(labels,expected);await choices.first().click();await enlarge();const nav=page.locator('.timeline-group-nav');assert.equal(await current(),29);assert(await nav.getByRole('button',{name:'Previous event',exact:true}).isDisabled());await nav.getByRole('button',{name:'Next event',exact:true}).click();await enlarge();assert.equal(await current(),30);assert(await nav.getByRole('button',{name:'Next event',exact:true}).isDisabled());assert(await diagram.isVisible());await nav.getByRole('button',{name:'Back to this pin\u2019s events',exact:true}).click();assert.deepEqual(await choices.allTextContents(),expected);record.labels=labels;
    await page.screenshot({path:path.join(out,'pin-group-americas-'+width+'-scale'+scale+'.png'),animations:'disabled'});
    await page.locator('#btnWorld').click();assert(await diagram.isHidden());assert.equal(await page.locator('#map .pin').count(),36,'Full journey restores36 geographic markers');assert.equal(await nav.count(),0);assert.equal(await page.locator('#map .pin').filter({hasText:/^(30|31)$/}).count(),0,'Unlocated events never acquire Earth markers');
    await filter('restoration');await page.locator('#timeline [data-stop-index="31"]').click();await enlarge();assert.equal(await current(),31);assert(await diagram.isHidden());assert.equal(await page.locator('#map .pin').count(),7);assert.equal(await page.locator('#map .pin--on').textContent(),'32');assert((await page.locator('#detail').textContent()).includes(await page.evaluate(()=>LifeTimeline.stops[31].title)));const figure=page.locator('[data-timeline-image="31"]');await figure.scrollIntoViewIfNeeded();await page.waitForFunction(()=>{const i=document.querySelector('[data-timeline-image="31"] img');return i&&i.complete&&i.naturalWidth>0;});assert.equal(await figure.locator('img').getAttribute('src'),await page.evaluate(()=>TimelineImages.registry.life[31].src));record.diagramWidth=await picture.evaluate(i=>i.naturalWidth);record.restorationSelected=32;assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+3));
   }else{
    await page.evaluate(kind=>window.__qaLeafletMaps[0].setView(kind==='history'?[53.5,-2.7]:[42,-109],kind==='history'?5:4,{animate:false}),kind);
    await page.locator('.leaflet-container').scrollIntoViewIfNeeded();
    const selector=kind==='history'?'.history-map-icon':'.handcart-cluster-icon';
    const choice=await page.locator(selector).evaluateAll((nodes,kind)=>{const b=document.querySelector('.leaflet-container').getBoundingClientRect();return nodes.map((n,i)=>{const r=n.getBoundingClientRect(),count=parseInt(n.textContent,10);return {i,count,x:r.x+r.width/2,y:r.y+r.height/2};}).filter(n=>n.count>1&&n.x>b.left+20&&n.x<b.right-20&&n.y>b.top+20&&n.y<b.bottom-20).sort((a,b)=>b.count-a.count)[0];},kind);assert(choice,'Visible multi-event map pin');await page.locator(selector).nth(choice.i).click();
    const choices=page.locator('.timeline-place-choices button:not(.timeline-choices-back)');const labels=await choices.allTextContents();assert(labels.length>1);
    const indices=await page.evaluate(({kind,labels})=>labels.map(label=>kind==='history'?window.HistoryTimeline.events.findIndex(e=>label.endsWith(e.title)):parseInt(label,10)-1),{kind,labels});assert(indices.every(i=>i>=0));record.labels=labels;record.indices=indices;
    await choices.first().click();await enlarge();const nav=page.locator('.timeline-group-nav');assert.equal(await current(),indices[0]);assert.equal(await nav.getByRole('button',{name:'Previous event',exact:true}).isDisabled(),true);
    for(let i=1;i<indices.length;i++){await nav.getByRole('button',{name:'Next event',exact:true}).click();await enlarge();assert.equal(await current(),indices[i],'Exact next member of original group');}
    assert.equal(await nav.getByRole('button',{name:'Next event',exact:true}).isDisabled(),true);await nav.getByRole('button',{name:'Previous event',exact:true}).click();await enlarge();assert.equal(await current(),indices[indices.length-2]);
    await page.locator('.leaflet-control-zoom-in').click();await page.waitForTimeout(350);assert.equal(await nav.count(),1,'Map zoom preserves selected group');
    await nav.getByRole('button',{name:'Back to this pin\u2019s events',exact:true}).click();assert.deepEqual(await choices.allTextContents(),labels,'Back retains exact original pin group after zoom');await choices.last().click();await enlarge();assert.equal(await current(),indices.at(-1));
    const geometry=await nav.evaluate(n=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,buttons:[...n.querySelectorAll('button')].map(b=>{const r=b.getBoundingClientRect();return {height:r.height,left:r.left,right:r.right};})}));assert(geometry.scrollWidth<=geometry.width+3);assert(geometry.buttons.every(b=>b.height>=44&&b.left>=-1&&b.right<=geometry.width+1),'Group controls remain readable contained44px targets');record.geometry=geometry;
    await nav.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(out,'pin-group-'+kind+'-'+width+'-scale'+scale+'.png'),animations:'disabled'});
    const disclosure=page.locator('.timeline-filter-disclosure');if(!(await disclosure.evaluate(n=>n.open)))await disclosure.locator(':scope > summary').click();if(kind==='history'){await page.locator('#search').fill('temple');}else await page.locator('[data-filter="willie"]').click();assert.equal(await nav.count(),0,'Filter clears old group');assert.equal(await page.locator('.timeline-place-choices').count(),0);record.filterCleared=true;
   }
   record.status='PASS';
  }catch(error){record.error=String(error);record.stack=error.stack;await page.screenshot({path:path.join(out,'pin-group-'+kind+'-'+width+'-scale'+scale+'-failure.png'),animations:'disabled'}).catch(()=>{});}records.push(record);
 }}finally{await page.unroute('https://**',intercept);fs.writeFileSync(path.join(out,'pin-groups.json'),JSON.stringify({evidence:'Real pinned Leaflet markers; simulated tiles; not physical-device acceptance',records},null,2));}
 assert.equal(records.length,12);assert.deepEqual(records.filter(r=>r.error),[],'Every pin group and ordinary Life navigation case must pass');return records;
};
