/* Hosted-browser geometry and independent scrolling checks for owner-requested timeline workspaces. */
const assert=require('node:assert/strict');
function assertControlInsets(m){assert(m.items.length>0,'Visible controls measured');for(const item of m.items){assert(item.left-m.left>=15.5&&m.right-item.right>=15.5,'Desktop control content needs16px horizontal breathing room '+JSON.stringify({m,item}));}}
assertControlInsets({left:0,right:200,items:[{left:16,right:184}]});assert.throws(()=>assertControlInsets({left:0,right:200,items:[{left:0,right:200}]}),'Zero-padding regression must fail');
module.exports=async function(page,origin,out){
 const fs=require('node:fs'),path=require('node:path'),records=[];
 for(const [width,height,scale] of [[1366,720,1],[1920,1080,1],[1366,500,1],[1366,900,2]])for(const [route,types] of [
  ['timelines/willie-and-martin-handcart-map.html',['events','map','detail']],
  ['timelines/life-of-christ-journey-map.html',['events','map','detail']],
  ['timelines/latter-day-saint-church-history-timeline.html',['events','map','timeline']]
 ]){
  const diagnostics={};try{await page.setViewportSize({width,height});await page.goto(origin+'/'+route,{waitUntil:'load'});
  const enlarge=()=>page.evaluate(scale=>{if(scale===1)return;const nodes=[...document.body.querySelectorAll('*')];nodes.forEach(n=>{if(n.dataset.qaTextScaled==='true')n.style.fontSize=n.dataset.qaOriginalFontSize;});const sizes=nodes.map(n=>parseFloat(getComputedStyle(n).fontSize));nodes.forEach((n,i)=>{if(n.dataset.qaTextScaled!=='true')n.dataset.qaOriginalFontSize=n.style.fontSize;n.style.fontSize=sizes[i]*scale+'px';n.dataset.qaTextScaled='true';});},scale);await enlarge();
  const workspace=page.locator('[data-timeline-workspace]');assert.equal(await workspace.count(),1,route+' one bounded workspace');
  const entry=page.locator(types.includes('timeline')?'.timeline-navigation a[href="#historyWorkspace"]':'a[href="#journeyWorkspace"]');await entry.click();await page.waitForFunction(()=>{const w=document.querySelector('[data-timeline-workspace]').getBoundingClientRect(),h=document.querySelector('[data-focuschrist-header="standard"]').getBoundingClientRect();return Math.abs(w.top-h.bottom-12)<=1&&w.bottom<=innerHeight+1;});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>requestAnimationFrame(r)))));const entryGeometry=await workspace.evaluate(n=>{const r=n.getBoundingClientRect(),main=n.closest('.wrap'),style=getComputedStyle(main),standard=parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--fc-standard')),gutter=parseFloat(style.paddingLeft),available=document.documentElement.clientWidth;return {top:r.top,bottom:r.bottom,left:r.left,right:r.right,width:r.width,standard,gutter,available,windowY:scrollY,headerBottom:document.querySelector('[data-focuschrist-header="standard"]').getBoundingClientRect().bottom};});assert(Math.abs(entryGeometry.width-Math.min(entryGeometry.standard,entryGeometry.available-2*entryGeometry.gutter))<=1,'Workspace follows shared horizontal boundary '+JSON.stringify(entryGeometry));assert(Math.abs(entryGeometry.left-(entryGeometry.available-entryGeometry.width)/2)<=1,'Workspace is centered within shared gutters');assert(Math.abs(entryGeometry.top-entryGeometry.headerBottom-12)<=1&&entryGeometry.bottom<=height+1,'Explore entry stays aligned after layout frames');
  const directSelection=await page.locator(types.includes('timeline')?'#eventDirectory button':route.includes('handcart')?'.stop-card':'#timeline .card').evaluateAll(nodes=>{const pane=document.querySelector('[data-timeline-pane="events"]').getBoundingClientRect(),header=document.querySelector('[data-focuschrist-header="standard"]').getBoundingClientRect();return nodes.map((n,index)=>{const r=n.getBoundingClientRect(),left=Math.max(r.left,pane.left),right=Math.min(r.right,pane.right),top=Math.max(r.top,pane.top,header.bottom),bottom=Math.min(r.bottom,pane.bottom,innerHeight);return {index,target:n.dataset.event,x:(left+right)/2,y:(top+bottom)/2,area:Math.max(0,right-left)*Math.max(0,bottom-top)};}).filter(r=>r.area>100).sort((a,b)=>b.area-a.area)[0];});assert(directSelection,'An actual visible event can be selected');const selectionWindowY=await page.evaluate(()=>scrollY);await page.mouse.click(directSelection.x,directSelection.y);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert(Math.abs(await page.evaluate(()=>scrollY)-selectionWindowY)<1,'Visible event selection does not move desktop document');if(types.includes('timeline'))assert.equal(await page.locator('#'+directSelection.target+' .card').evaluate(n=>n.classList.contains('open')),true);else assert.equal(await page.evaluate(handcart=>handcart?window.HandcartTimeline.current:window.LifeTimeline.current,route.includes('handcart')),directSelection.index,'Exact visible map-event selection');
  if(types.includes('detail')){const cards=page.locator(route.includes('handcart')?'.stop-card':'#timeline .card');let longest={index:0,length:0};for(let i=0;i<await cards.count();i++){await cards.nth(i).click();const length=(await page.locator('[data-timeline-pane="detail"]').innerText()).length;if(length>longest.length)longest={index:i,length};}await cards.nth(longest.index).click();}
  await enlarge();await workspace.evaluate(n=>n.scrollIntoView({block:'start',behavior:'instant'}));
  await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  const snapshot=()=>page.evaluate(types=>{const box=n=>{const r=n.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom,right:r.right};};return {windowY:scrollY,viewport:innerHeight,header:box(document.querySelector('nav[data-focuschrist-header="standard"]')),controls:document.querySelector('.controls')?box(document.querySelector('.controls')):null,panes:types.map(type=>{const n=document.querySelector('[data-timeline-pane="'+type+'"]');return {type,...box(n),scrollTop:n.scrollTop,scrollHeight:n.scrollHeight,clientHeight:n.clientHeight,overflow:getComputedStyle(n).overflowY};})};},types);
  await page.locator('[data-timeline-pane="events"]').evaluate(n=>n.scrollTop=0);
  const controlInsets=await page.locator('.controls').evaluate(n=>{const r=n.getBoundingClientRect();return {left:r.left,right:r.right,items:[...n.querySelectorAll('button,input,label,summary,.count-label,.count-note')].filter(c=>c.getClientRects().length&&c.getBoundingClientRect().width>0).map(c=>{const b=c.getBoundingClientRect();return {tag:c.tagName,text:(c.textContent||c.getAttribute('placeholder')||'').trim().slice(0,80),left:b.left,right:b.right};})};});assertControlInsets(controlInsets);const textInsets=await page.locator('.controls').evaluate(n=>{const b=n.getBoundingClientRect(),items=[],w=document.createTreeWalker(n,NodeFilter.SHOW_TEXT);let t;while(t=w.nextNode()){if(!t.textContent.trim())continue;const r=document.createRange();r.selectNodeContents(t);for(const q of r.getClientRects())if(q.width&&q.height)items.push({text:t.textContent.trim().slice(0,80),left:q.left,right:q.right});}return {left:b.left,right:b.right,items};});assertControlInsets(textInsets);diagnostics.controlInsets={elements:controlInsets,text:textInsets};
  const initial=await snapshot();if(types.includes('detail')){const filters=await page.locator('.controls').evaluate(n=>({position:getComputedStyle(n).position,top:getComputedStyle(n).top,client:n.clientHeight,scroll:n.scrollHeight,box:n.getBoundingClientRect().toJSON(),children:[...n.querySelectorAll('button')].map(b=>b.getBoundingClientRect().toJSON())}));assert.equal(filters.position,'relative','Desktop filters must use bounded workspace flow');assert(filters.top==='auto'||parseFloat(filters.top)===0,'Relative filters have no vertical offset');assert(filters.scroll<=filters.client+2,'Desktop filter row is not clipped '+JSON.stringify(filters));assert(filters.children.every(b=>b.top>=filters.box.top-1&&b.bottom<=filters.box.bottom+1),'Every filter button fits its row');}if(types.includes('timeline')){assert.equal(await page.locator('#historyDirectory').evaluate(n=>getComputedStyle(n).overflowY),'visible','Directory wrapper must not add a redundant clipping ancestor');assert.equal(await page.locator('#eventDirectory').evaluate(n=>getComputedStyle(n).overflowY),'auto','Actual event pane retains scroll containment');}
  for(let i=0;i<initial.panes.length;i++){const pane=initial.panes[i];assert(pane.height>=(height===500?120:200),route+' usable '+pane.type+' height');assert(pane.y>=initial.header.bottom-1&&(types.includes('timeline')||!initial.controls||pane.y>=initial.controls.bottom-1),route+' '+pane.type+' below menu and filters');assert(pane.bottom<=height+1,route+' '+pane.type+' bounded by viewport');if(i)assert(pane.x>=initial.panes[i-1].right-1,route+' left-to-right pane order');}
  const events=page.locator('[data-timeline-pane="events"]');assert(initial.panes[0].scrollHeight>initial.panes[0].clientHeight+20,route+' event directory actually scrolls');
  const bounds=await events.boundingBox();await page.mouse.move(bounds.x+bounds.width/2,bounds.y+Math.min(80,bounds.height/2));await page.mouse.wheel(0,250);
  await page.waitForFunction(()=>document.querySelector('[data-timeline-pane="events"]').scrollTop>10);
  const after=await snapshot();assert(Math.abs(after.windowY-initial.windowY)<1,route+' event wheel leaves document fixed');for(let i=1;i<after.panes.length;i++){assert(Math.abs(after.panes[i].y-initial.panes[i].y)<1,route+' event wheel leaves sibling geometry fixed');assert.equal(after.panes[i].scrollTop,initial.panes[i].scrollTop,route+' event wheel leaves sibling scroll fixed');}
  let detailAfter=null;if(types.includes('detail')){const detail=after.panes.find(p=>p.type==='detail');if(height===500)assert(detail.scrollHeight>detail.clientHeight+20,route+' long story has independent overflow');if(detail.scrollHeight>detail.clientHeight+20){const pane=page.locator('[data-timeline-pane="detail"]');await pane.evaluate(n=>n.scrollTop=0);const b=await pane.boundingBox(),before=await snapshot();await page.mouse.move(b.x+b.width/2,b.y+60);await page.mouse.wheel(0,200);await page.waitForFunction(()=>document.querySelector('[data-timeline-pane="detail"]').scrollTop>10);detailAfter=await snapshot();assert(Math.abs(detailAfter.windowY-before.windowY)<1,'Detail wheel leaves document fixed');for(const kind of ['events','map'])assert.equal(detailAfter.panes.find(p=>p.type===kind).scrollTop,before.panes.find(p=>p.type===kind).scrollTop,'Detail wheel leaves '+kind+' fixed');}}
  let historySelection=null;if(types.includes('timeline')){const visibleChoice=await page.locator('#eventDirectory button').evaluateAll(nodes=>{if(!nodes.length)return null;const p=nodes[0].parentElement.getBoundingClientRect();return nodes.map((n,i)=>{const r=n.getBoundingClientRect(),left=Math.max(r.left,p.left,0),right=Math.min(r.right,p.right,innerWidth),top=Math.max(r.top,p.top,0),bottom=Math.min(r.bottom,p.bottom,innerHeight);return {i,target:n.dataset.event,x:(left+right)/2,y:(top+bottom)/2,width:right-left,height:bottom-top,area:Math.max(0,right-left)*Math.max(0,bottom-top)};}).filter(x=>x.width>8&&x.height>8).sort((a,b)=>b.area-a.area)[0]||null;});assert(visibleChoice,'A visible event-button intersection remains clickable');const before=await snapshot(),target=visibleChoice.target;await page.mouse.click(visibleChoice.x,visibleChoice.y);historySelection=await snapshot();assert(Math.abs(historySelection.windowY-before.windowY)<1,'History selection leaves document fixed');assert.equal(historySelection.panes[0].scrollTop,before.panes[0].scrollTop,'History selection leaves directory scroll fixed');assert.equal(await page.locator('#'+target+' .card').evaluate(n=>n.classList.contains('open')),true,'Directory opens exact event inline');assert.equal(await page.locator('#timeline .event:not([hidden])').count(),1,'Directory presents exactly one complete story');await page.evaluate(()=>{const events=HistoryTimeline.events;const i=events.reduce((best,e,i)=>JSON.stringify(e).length>JSON.stringify(events[best]).length?i:best,0);HistoryTimeline.select(i);});const reader=page.locator('[data-timeline-pane="timeline"]');await reader.evaluate(n=>n.scrollTop=0);const b=await reader.boundingBox(),start=await snapshot();await page.mouse.move(b.x+b.width/2,b.y+80);await page.mouse.wheel(0,250);await page.waitForFunction(()=>document.querySelector('[data-timeline-pane="timeline"]').scrollTop>10);const end=await snapshot();assert(Math.abs(end.windowY-start.windowY)<1&&end.panes[0].scrollTop===start.panes[0].scrollTop,'Timeline wheel leaves document and directory fixed');}
  await page.screenshot({path:path.join(out,'panes-'+width+'x'+height+'-scale'+scale+'-'+path.basename(route,'.html')+'.png'),animations:'disabled'});const edgeAncestors=await events.evaluate(n=>{const records=[];for(let p=n;p&&p!==document.body;p=p.parentElement){if(p.scrollHeight>p.clientHeight+1&&['auto','scroll'].includes(getComputedStyle(p).overflowY)){p.scrollTop=p.scrollHeight;records.push({id:p.id,class:p.className,scrollTop:p.scrollTop,scrollHeight:p.scrollHeight,clientHeight:p.clientHeight,overscroll:getComputedStyle(p).overscrollBehaviorY});}}return records;});const edgeBox=await events.boundingBox(),beforeEdge=await page.evaluate(()=>scrollY),edgePoint={x:edgeBox.x+edgeBox.width/2,y:edgeBox.y+Math.min(80,edgeBox.height/2)};
  const edgeState=()=>page.evaluate(point=>{const hit=document.elementFromPoint(point.x,point.y),chain=[];for(let n=hit;n;n=n.parentElement){const cs=getComputedStyle(n);chain.push({tag:n.tagName,id:n.id,class:n.className,scrollTop:n.scrollTop,scrollHeight:n.scrollHeight,clientHeight:n.clientHeight,overflow:cs.overflowY,overscroll:cs.overscrollBehaviorY});}return {windowY:scrollY,documentHeight:document.documentElement.scrollHeight,viewport:innerHeight,point,chain};},edgePoint);
  await page.mouse.move(edgePoint.x,edgePoint.y);
  // A new gesture must not inherit Chromium's previous reader-wheel scroll latch.
  await page.waitForTimeout(400);diagnostics.edge={ancestors:edgeAncestors,before:await edgeState()};await page.mouse.wheel(0,350);
  try{await page.waitForFunction(y=>scrollY>y+15,beforeEdge,{timeout:5000});}finally{diagnostics.edge.after=await edgeState();}
const edgeRelease={ancestors:edgeAncestors,before:beforeEdge,after:await page.evaluate(()=>scrollY)};records.push({route,width,height,scale,entryGeometry,directSelection,selectionWindowY,initial,after,detailAfter,historySelection,edgeRelease,diagnostics,status:'PASS'});
  }catch(error){records.push({route,width,height,scale,error:String(error),stack:error.stack,diagnostics});await page.screenshot({path:path.join(out,'panes-'+width+'x'+height+'-scale'+scale+'-'+path.basename(route,'.html')+'-failure.png'),animations:'disabled'}).catch(()=>{});}
 }
 fs.writeFileSync(path.join(out,'independent-panes.json'),JSON.stringify(records,null,2));assert.equal(records.length,12);assert.deepEqual(records.filter(r=>r.error),[],'All independent-pane profiles must pass');return records;
};
