/* Production shared controller in JSDOM: DOM/state ownership only, rendered scrolling is hosted QA. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{JSDOM}=require('jsdom');
const source=fs.readFileSync(path.join(__dirname,'../timeline-workspace.js'),'utf8');
for(const desktop of [false,true]){
 const dom=new JSDOM('<nav data-focuschrist-header="standard"></nav><section id="journeyWorkspace" data-timeline-workspace><div data-timeline-pane="events" style="overflow:auto"><button id="original">Original event</button></div><div data-timeline-pane="map"><div id="map"></div></div><div data-timeline-pane="detail">Story</div></section>',{url:'https://focuschrist.com/timelines/test.html',runScripts:'outside-only'}),w=dom.window,d=w.document;
 const media={matches:desktop,addEventListener(name,fn){this.change=fn;}};w.matchMedia=()=>media;w.requestAnimationFrame=()=>1;w.scrollTo=()=>{};
 let selected=null,visible=Array.from({length:22},(_,i)=>i);w.TimelineNavigationAdapter={visibleIndices:()=>visible,current:()=>selected,select:index=>{selected=index;w.dispatchEvent(new w.CustomEvent('timeline:select',{detail:{index}}));}};const interaction=[];d.getElementById('map').addEventListener('timeline:map-interaction',e=>interaction.push(e.detail.enabled));w.eval(source);assert.equal(interaction.at(-1),desktop,'Map pan defaults to desktop only');const api=w.TimelineWorkspace,events=d.querySelector('[data-timeline-pane="events"]'),workspace=d.querySelector('[data-timeline-workspace]'),original=d.getElementById('original');const choices=[{index:3,label:'4. Exact fourth event'},{index:19,label:'20. Exact twentieth event'}];
 const open=()=>api.showChoices('Nearby events',choices,index=>{selected=index;w.dispatchEvent(new w.CustomEvent('timeline:select',{detail:{index}}));});
 events.scrollTop=137;assert.equal(open(),true);
 let panel=d.querySelector('.timeline-place-choices');assert.equal(panel.parentElement,events,'Choices use the actual Events container; rendered overflow is verified separately');assert(events.classList.contains('timeline-choice-mode'));assert.equal(original.parentElement,events,'Full matching events remain intact');assert.equal(events.scrollTop,0);assert.equal(workspace.dataset.mobileView,'events');assert.equal(d.activeElement,panel.querySelector('h3'));
 assert.deepEqual([...panel.querySelectorAll('button')].slice(1).map(n=>n.textContent),choices.map(c=>c.label));panel.querySelectorAll('button')[2].click();assert.equal(selected,19);assert.equal(d.querySelector('.timeline-place-choices'),null);assert(!events.classList.contains('timeline-choice-mode'));assert.equal(events.scrollTop,137);assert.equal(workspace.dataset.mobileView,desktop?'events':'story');

 let nav=d.querySelector('.timeline-group-nav');assert(nav,'Selected story retains Back to original pin');assert.equal(nav.querySelectorAll('button').length,1,'Only Back belongs to pin context');
 let next=()=>d.querySelector('[data-event-direction="1"]'),previous=()=>d.querySelector('[data-event-direction="-1"]');
 previous().click();assert.equal(selected,18,'Previous uses chronological adjacent event, not other pin member');next().click();assert.equal(selected,19);next().click();assert.equal(selected,20,'Next continues outside original pin group');
 d.querySelector('.timeline-group-nav button').click();assert.deepEqual([...d.querySelectorAll('.timeline-place-choices button')].slice(1).map(n=>n.textContent),choices.map(c=>c.label),'Back preserves original pin even after leaving its members');
 d.querySelectorAll('.timeline-place-choices button')[2].click();assert.equal(selected,19);d.querySelector('.timeline-group-nav button').click();assert.equal(d.querySelector('[aria-current="true"]').textContent,choices[1].label);
 const staleChoice=d.querySelectorAll('.timeline-place-choices button')[1];api.showChoices('Different pin',[{index:8,label:'9. Other'},{index:12,label:'13. Other'}],index=>{selected=index;w.dispatchEvent(new w.CustomEvent('timeline:select',{detail:{index}}));});staleChoice.click();assert.equal(selected,19,'Detached prior pin callback cannot select');d.querySelectorAll('.timeline-place-choices button')[1].click();assert.equal(selected,8);w.dispatchEvent(new w.Event('resize'));assert(d.querySelector('.timeline-group-nav'),'Resize/zoom does not discard group');w.dispatchEvent(new w.CustomEvent('timeline:filter'));assert.equal(d.querySelector('.timeline-group-nav'),null);visible=[3,8,19];assert.equal(api.stepEvent(1),true);assert.equal(selected,19,'Filtered Next skips hidden entries');assert(next().disabled,'Last visible event disables Next');previous().click();assert.equal(selected,8);previous().focus();previous().click();assert.equal(d.activeElement.getAttribute('data-event-direction'),'1','Boundary retains focus on enabled opposite control');assert.equal(selected,3);assert(previous().disabled,'First visible event disables Previous');
 api.clearGroup();selected=19;
 api.showEvents();events.scrollTop=75;open();d.querySelector('.timeline-choices-back').click();assert.equal(d.querySelector('.timeline-place-choices'),null);assert.equal(events.scrollTop,75);assert.equal(workspace.dataset.mobileView,'events');assert.equal(selected,19,'Cancellation does not choose a story');assert.equal(original.parentElement,events);
 open();w.dispatchEvent(new w.CustomEvent('timeline:filter',{detail:{indices:[3]}}));assert.equal(d.querySelector('.timeline-place-choices'),null);assert.equal(workspace.dataset.mobileView,'events');assert.equal(original.parentElement,events);
 open();api.showStory();assert.equal(d.querySelector('.timeline-place-choices'),null);assert.equal(workspace.dataset.mobileView,desktop?'events':'story');
 open();media.matches=true;if(media.change)media.change();assert.equal(d.querySelector('.timeline-place-choices'),null,'Desktop transition restores ordinary event list');
 if(!desktop){media.matches=false;media.change();const interact=d.querySelector('.timeline-map-interact');assert.equal(interact.getAttribute('aria-pressed'),'false');interact.click();assert.equal(interact.getAttribute('aria-pressed'),'true');assert.equal(interaction.at(-1),true);interact.click();assert.equal(interact.getAttribute('aria-pressed'),'false');assert.equal(interaction.at(-1),false);}
 dom.window.close();
}
{
 const dom=new JSDOM('<section data-timeline-workspace><nav data-timeline-pane="events"></nav><div data-timeline-pane="map"><div id="map"></div></div><main data-timeline-pane="timeline"><article id="history-event-0"></article></main></section>',{runScripts:'outside-only'}),w=dom.window;w.matchMedia=()=>({matches:false,addEventListener(){}});w.requestAnimationFrame=()=>1;w.HistoryTimeline={selectedIndex:0};w.eval(source);assert.equal(w.document.querySelector('[data-timeline-workspace]').dataset.mobileView,'story','Late controller preserves an earlier History selection');dom.window.close();
}
for(const [route,workspaceClass] of [['history','history-workspace'],['handcart',''],['life','']]){
 const dom=new JSDOM('<section class="'+workspaceClass+'" data-timeline-workspace><div id="parent" style="overflow-y:auto"><nav data-timeline-pane="events" style="overflow-y:auto;line-height:20px"><button>Event</button></nav></div><div data-timeline-pane="map"><div id="map"></div></div><main data-timeline-pane="timeline"></main></section>',{runScripts:'outside-only'}),w=dom.window,d=w.document,media={matches:true,addEventListener(){}};w.matchMedia=()=>media;w.requestAnimationFrame=()=>1;const moves=[];w.scrollBy=options=>moves.push(options.top);w.eval(source);const events=d.querySelector('nav'),parent=d.getElementById('parent');for(const [node,height,client] of [[events,1000,200],[parent,300,200]]){Object.defineProperty(node,'scrollHeight',{value:height});Object.defineProperty(node,'clientHeight',{value:client});}
 const wheel=(dy,extra={})=>{const event=new w.WheelEvent('wheel',{deltaY:dy,bubbles:true,cancelable:true,...extra});events.querySelector('button').dispatchEvent(event);return event.defaultPrevented;};
 events.scrollTop=400;parent.scrollTop=100;assert.equal(wheel(100),false,'Mid-directory wheel remains native');assert.equal(moves.length,0);
 events.scrollTop=800;parent.scrollTop=0;assert.equal(wheel(100),false,'Scrollable ancestor consumes before document');parent.scrollTop=100;assert.equal(wheel(100),true);assert.deepEqual(moves,[100],route+' exhausted event pane releases to document');assert.equal(wheel(2,{deltaMode:1}),true);assert.equal(moves.at(-1),40,'Line wheel units normalized');assert.equal(wheel(1,{deltaMode:2}),true);assert.equal(moves.at(-1),w.innerHeight,'Page wheel units normalized');
 events.scrollTop=0;parent.scrollTop=0;assert.equal(wheel(-80),true);assert.equal(moves.at(-1),-80,'Top edge releases upward');const count=moves.length;assert.equal(wheel(100,{ctrlKey:true}),false);assert.equal(wheel(100,{shiftKey:true}),false);assert.equal(wheel(10,{deltaX:100}),false);media.matches=false;assert.equal(wheel(-100),false);assert.equal(moves.length,count,'Zoom horizontal and mobile gestures untouched');dom.window.close();
}
{
 const dom=new JSDOM('<section data-timeline-workspace><nav data-timeline-pane="events"><button>Full events</button></nav><div data-timeline-pane="map"><div id="map"></div></div><main data-timeline-pane="timeline"><article id="history-event-3"><div class="timeline-event-navigation-slot"></div></article><article id="history-event-4"><div class="timeline-event-navigation-slot"></div></article></main></section>',{runScripts:'outside-only'}),w=dom.window,d=w.document;w.matchMedia=()=>({matches:false,addEventListener(){}});w.requestAnimationFrame=()=>1;w.HistoryTimeline={selectedIndex:null};w.TimelineNavigationAdapter={current:()=>w.HistoryTimeline.selectedIndex,visibleIndices:()=>[3,4],select:index=>{w.HistoryTimeline.selectedIndex=index;w.dispatchEvent(new w.CustomEvent('timeline:select',{detail:{index}}));}};w.eval(source);w.TimelineWorkspace.showChoices('England',[{index:3,label:'Fourth event'},{index:19,label:'Twentieth event'}],w.TimelineNavigationAdapter.select);d.querySelectorAll('.timeline-place-choices button')[1].click();assert.equal(d.querySelector('.timeline-event-navigation').closest('article').id,'history-event-3');d.querySelector('[data-event-direction="1"]').click();assert.equal(d.querySelector('.timeline-event-navigation').closest('article').id,'history-event-4','History Next follows chronological list');assert.equal(d.querySelectorAll('.timeline-event-navigation').length,1);d.querySelector('.timeline-group-nav button').click();assert.equal(d.querySelectorAll('.timeline-place-choices button').length,3,'Original nonadjacent pin retained');dom.window.close();
}
console.log('PASS: choices at every width occupy the real Events pane, preserve full list and scroll position, select exact story, cancel/filter/view/desktop transitions clear choices; map interaction is explicit on phones.');

// Bottom controls share filtered order and return keyboard focus to the new story.
{
 const dom=new JSDOM('<section class="history-workspace" data-timeline-workspace data-mobile-breakpoint="1099"><nav data-timeline-pane="events"><button id="row">Event</button></nav><div data-timeline-pane="map"><div id="map"></div></div><main data-timeline-pane="timeline">'+[3,8].map(i=>'<article id="history-event-'+i+'"><div class="timeline-event-navigation-slot"></div><div class="detail"><figure>Picture and caption</figure></div><div class="timeline-event-navigation-bottom-slot"></div></article>').join('')+'</main></section>',{runScripts:'outside-only'}),w=dom.window,d=w.document;
 const media={matches:false,addEventListener(){}};w.matchMedia=()=>media;w.requestAnimationFrame=()=>1;
 let selected=3,visible=[3,8];w.HistoryTimeline={get selectedIndex(){return selected;}};
 w.TimelineNavigationAdapter={current:()=>selected,visibleIndices:()=>visible,select:index=>{selected=index;w.dispatchEvent(new w.CustomEvent('timeline:select',{detail:{index}}));}};
 w.eval(source);
 const top=()=>d.querySelector('#history-event-'+selected+' .timeline-event-navigation-slot');
 const bottom=()=>d.querySelector('#history-event-'+selected+' .timeline-event-navigation-bottom-slot');
 assert.equal(d.querySelectorAll('.timeline-event-navigation').length,2,'Only the selected story has top and bottom navigation');
 assert(bottom().previousElementSibling.classList.contains('detail'),'Bottom navigation follows the whole reading and figure container');
 assert(bottom().querySelector('[data-event-direction="-1"]').disabled,'First filtered event has disabled Previous');
 let next=bottom().querySelector('[data-event-direction="1"]');next.focus();next.click();
 assert.equal(selected,8,'Bottom Next follows filtered indices rather than index+1');
 assert(bottom().querySelector('[data-event-direction="1"]').disabled,'Last filtered event has disabled Next');
 assert.equal(d.activeElement,top().querySelector('[data-event-direction="-1"]'),'At last event focus returns to enabled top Previous');
 assert.equal(d.querySelectorAll('.timeline-event-navigation').length,2,'Old story navigation is removed');
 let previous=bottom().querySelector('[data-event-direction="-1"]');previous.focus();previous.click();
 assert.equal(selected,3);assert.equal(d.activeElement,top().querySelector('[data-event-direction="1"]'),'At first event focus returns to enabled top Next');
 visible=[3];w.dispatchEvent(new w.CustomEvent('timeline:filter'));assert([...d.querySelectorAll('.timeline-event-navigation button')].every(b=>b.disabled),'Single matching event disables both controls in both locations');
 visible=[];w.dispatchEvent(new w.CustomEvent('timeline:filter'));assert.equal(d.querySelectorAll('.timeline-event-navigation').length,0,'Empty filter removes all navigation');
 media.matches=true;const pane=d.querySelector('[data-timeline-pane="events"]'),row=d.getElementById('row');pane.getBoundingClientRect=()=>({top:100,bottom:300});row.getBoundingClientRect=()=>({top:310,bottom:360});pane.scrollTop=0;w.TimelineWorkspace.scrollRow(row);assert.equal(pane.scrollTop,63,'Reveal lower row within its event pane');row.getBoundingClientRect=()=>({top:70,bottom:120});w.TimelineWorkspace.scrollRow(row);assert.equal(pane.scrollTop,30,'Reveal upper row within its event pane');
 dom.window.close();
}

// Generic journey detail panes use the same filtered navigation contract as History.
for(const tag of ['section','aside']){
 const dom=new JSDOM('<section data-timeline-workspace><nav data-timeline-pane="events"></nav><div data-timeline-pane="map"><div id="map"></div></div><'+tag+' data-timeline-pane="detail"><div class="timeline-event-navigation-slot"></div><p>Story</p><figure>Picture and caption</figure><div class="timeline-event-navigation-bottom-slot"></div></'+tag+'></section>',{runScripts:'outside-only'}),w=dom.window,d=w.document;
 w.matchMedia=()=>({matches:false,addEventListener(){}});w.requestAnimationFrame=()=>1;let current=2,visible=[2,7];w.TimelineNavigationAdapter={current:()=>current,visibleIndices:()=>visible,select:index=>{current=index;w.dispatchEvent(new w.CustomEvent('timeline:select',{detail:{index}}));}};w.eval(source);
 const bottom=()=>d.querySelector('.timeline-event-navigation-bottom-slot'),top=()=>d.querySelector('.timeline-event-navigation-slot');
 assert.equal(d.querySelectorAll('.timeline-event-navigation').length,2);let next=bottom().querySelector('[data-event-direction="1"]');next.focus();next.click();assert.equal(current,7);assert(bottom().querySelector('[data-event-direction="1"]').disabled);assert.equal(d.activeElement,top().querySelector('[data-event-direction="-1"]'));bottom().querySelector('[data-event-direction="-1"]').click();assert.equal(current,2);assert(bottom().querySelector('[data-event-direction="-1"]').disabled);assert.equal(d.querySelectorAll('.timeline-event-navigation').length,2);
 visible=[];w.dispatchEvent(new w.CustomEvent('timeline:filter'));assert.equal(d.querySelectorAll('.timeline-event-navigation').length,0);dom.window.close();
}
