const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const root=path.join(__dirname,'..'),source=fs.readFileSync(path.join(root,'timeline-images.js'),'utf8');
for(const [route,kind,count] of [['life-of-christ-journey-map.html','life',38],['willie-and-martin-handcart-map.html','handcart',33],['latter-day-saint-church-history-timeline.html','history',51]]){
 const dom=new JSDOM('<div data-timeline-pane="detail"><p id="story">Original narrative</p><div class="timeline-event-navigation-bottom-slot"></div></div>'+Array.from({length:51},(_,i)=>'<article id="history-event-'+i+'"><div class="detail"><p>Original story '+i+'</p></div></article>').join(''),{url:'https://focuschrist.com/timelines/'+route,runScripts:'outside-only'}),w=dom.window,d=w.document;w.eval(source);
 if(kind!=='history')assert(d.querySelector('[data-timeline-image]').nextElementSibling.classList.contains('timeline-event-navigation-bottom-slot'),'Initial picture precedes bottom navigation');
 const registry=w.TimelineImages.registry[kind];assert.equal(Object.keys(registry).length,count);assert.equal(d.querySelectorAll('[data-timeline-image]').length,kind==='history'?0:1);assert.equal(new Set(Object.values(registry).map(r=>r.src)).size,count);
 assert.deepEqual(Object.keys(registry),Array.from({length:count},(_,i)=>String(i)),'Every original index has one image');
 for(const [index,entry] of Object.entries(registry)){
  w.dispatchEvent(new w.CustomEvent('timeline:select',{detail:{index:Number(index)}}));const figures=d.querySelectorAll('[data-timeline-image]');assert.equal(figures.length,kind==='history'?Number(index)+1:1);const f=d.querySelector('[data-timeline-image="'+index+'"]');assert.equal(f.dataset.timelineImage,index);assert.equal(f.querySelector('img').getAttribute('src'),entry.src);assert.equal(f.querySelector('a').getAttribute('href'),entry.href);assert.equal(d.getElementById('story').textContent,'Original narrative');if(kind==='history')assert.equal(f.parentElement.parentElement.id,'history-event-'+index);else assert(f.nextElementSibling.classList.contains('timeline-event-navigation-bottom-slot'),'Every selected picture and caption precedes bottom controls');
  assert(fs.existsSync(path.join(root,entry.src)));assert(entry.width>0&&entry.height>0);assert.equal(f.querySelector('img').width,entry.width);assert.equal(f.querySelector('img').height,entry.height);assert.equal(f.querySelector('img').alt,entry.alt);assert(entry.alt.length>15&&entry.caption.length>20);
  if(entry.href.startsWith('/')){const [page,anchor]=entry.href.slice(1).split('#'),owner=fs.readFileSync(path.join(root,page),'utf8');if(anchor)assert(owner.includes('id="'+anchor+'"'));assert(owner.includes(entry.src)||owner.includes(entry.src.slice(1)),'owning page contains referenced asset '+entry.src);}
  else{assert(entry.href.startsWith('https://'));assert.equal(typeof entry.credit,'string');assert(entry.credit.length>3);assert(f.querySelector('figcaption').textContent.includes(entry.credit));assert.equal(f.querySelector('a').rel,'noopener noreferrer');assert(!/No known restrictions|ipCode|CODE_/.test(f.querySelector('figcaption').textContent));}
  if(entry.frame){assert.equal(kind,'life');assert.equal(index,'15');assert.equal(entry.frame,'banias-photo');assert.equal(f.querySelector('a').dataset.imageFrame,entry.frame);}
 }
 w.dispatchEvent(new w.CustomEvent('timeline:select',{detail:{index:999}}));assert.equal(d.querySelectorAll('[data-timeline-image]').length,kind==='history'?count:0);
 w.TimelineImages.render(0);w.dispatchEvent(new w.CustomEvent('timeline:filter',{detail:{indices:[]}}));assert.equal(d.querySelectorAll('[data-timeline-image]').length,0);if(kind!=='history'){w.TimelineImages.render(0);assert(d.querySelector('[data-timeline-image]').nextElementSibling.classList.contains('timeline-event-navigation-bottom-slot'),'Filter then reselection retains picture-before-controls order');}
 w.HistoryTimeline={selectedIndex:8};w.LifeTimeline={current:8};w.HandcartTimeline={current:8};w.eval(source);assert.equal(d.querySelector('[data-timeline-image]').dataset.timelineImage,'8','Early selected story receives its matching image');dom.window.close();
}
console.log('PASS122 image references unique per experience, assets/owning links valid, visible credits, exact selected container, initial selection rules, stale image removal, narrative retained.');
